### ISSUE TITLE
New Line Character not working in pyscript.write's string

### ISSUE THREAD

**Issue by thenithinbalaji** [pyscript/pyscript#540] opened 2022-06-22 19:39 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When a New line character is given in pyscript.write, the pyscript fails to render the new line character in the element. 
```py
pyscript.write('textBox', f'{inputStr} \n {outputStr}')
```
Expected to see in textBox
```
input
output
```
But the textBox has
```
input output
```

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by thenithinbalaji** [comment] 2022-06-25 19:48
any workarounds? 🤔

**Comment by amgawishx** [comment] 2022-07-02 20:30
Can you please post the HTML you used or the important part of it? I am unable to produce this issue.

**Comment by thenithinbalaji** [comment] 2022-07-03 07:41
HTML

```html
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    </head>

  <body>
    <button id = "button1" pys-onClick = "buttonpresses()">Press me!</button>
    <br>
    <div id = "para"></div>
    
    <py-script>
        def buttonpresses():
            pyscript.write('para', f'Hello World! \nThis is second line \nThis is third line')
    
    </py-script>
  </body>
</html>
```

**Comment by thenithinbalaji** [comment] 2022-07-03 07:43
@amgawishx Thanks for asking, I forgot to put this when I raised the issue

**Comment by tedpatrick** [comment] 2022-09-26 01:57
The HTML DOM ignores newlines. Here is an example showing the newlines are preserved in DOM writing but the browser is simply not rendering this whitespace.

Example
```html
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/unstable/pyscript.css" />
      <script defer src="https://pyscript.net/unstable/pyscript.js"></script>
    </head>
  <body>
    <button id="mybutton" py-click="button_click()">Press me!</button>
    <br>
    <div id = "para"></div>
    
    <py-script>
para = Element("para")
def button_click():
    para.element.innerHTML = f'Hello World! \nThis is second line \nThis is third line'
    </py-script>
  </body>
</html>
```

I am looking at the mime-type support built into the `write` function.

**Comment by marimeireles** [comment] 2022-09-26 12:06
Thanks for opening the issue @thenithinbalaji, I can reproduce this behavior. (Also on my newer implementation of the `display` method).
But... as @tedpatrick mentioned seems like this is a expected behavior by HTML?
One fix I found was changing HTML:

```
body {
      white-space: pre-wrap;
  }
```

But not sure if it's a good fix as it seems like it changes a lot of things around.

**Comment by WebReflection** [comment] 2023-12-07 09:38
This is not actionable for us, it's a standard behavior that can be easily fixed via CSS as previously suggested.

Closing as there's no issue to fix (we can't transform automatically new lines in `<br>` because that breaks in other places such as textareas and we can't apply random style as that would be obtrusive).

**Closed by WebReflection** 2023-12-07 09:38 UTC
Labels: type: bug, backlog
