### ISSUE TITLE
Create a new API/feature for uploading files to PyScript

### ISSUE THREAD

**Issue by andreaslam** [pyscript/pyscript#558] opened 2022-06-27 15:33 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

The feature I want is to allow local files to be easily accessible on the virtual file system/file server (Due to security reasons, browsers do not allow fetching a file in local file system). 

I would like to request for a feature where all local files are uploaded to a centralised location (to increase user friendliness I suggest to have the upload format similar to Google Drive, drag and drop folders or files) and be able to access those files through an API when needed. I know this sounds like a regular backend solution but a solution for the sake of simplicity and testing purposes would be much appreciated. 

I have contacted developers of Pyodide but they have a lot of work to do and they don't have a concrete plan on releasing a file system API over there hence I am requesting this feature here. 

Thank you!

### Why is this needed

 The project I am working on needs to use and access local files. I do not plan on using a backend as of now as I am just in the testing stage. 

### What should happen?

The user uploads folders/files to a centralised location and get an API key to paste into their code and can have access to those files if needed.

**Comment by marimeireles** [comment] 2022-09-08 11:29
Closing it as dup. please redirect any questions related to the topic to the [documentation issue](#756 ).
If you're facing a different problem or think might have encountered a bug please feel free to open a new issue.
If I misinterpreted your issue and you think it should still be open please reply here and we'll reopen it.
Thank you!

**Comment by marimeireles** [comment] 2022-09-08 11:30
Actually, I'm sorry this is not a dup. This is the actual request for the API.
Will keep it open to keep it in mind.
If anyone wants to pick it up, please feel free!
Just ping me or some of the other maintainers and we can start a discussion on the best way of doing it.
Otherwise, it's in our backlog to tackle this.

**Comment by marianoweber** [comment] 2022-09-08 21:32
If I understand that correctly, that would be similar to #463. Which is outdated and can be simplified much more, but maybe it's a starting point.
It uses the MEMFS but could mount IDBFS files to persist through page reloads.

**Comment by marimeireles** [comment] 2022-09-12 12:02
Yes @marianoweber.
My hope is that the team will have more ability to focus on it by the end of September...
But I think this is a relevant issue we should tackle sooner rather than later, so I'm marking it here to bring it up in the next meeting.
Will update this issue soon with what I learn.
Thanks!

**Comment by WebReflection** [comment] 2024-01-22 15:11
Closing as half duplicate of https://github.com/pyscript/pyscript/issues/1050 where once that's done nobody would need an API but because the PyDom API progress is not shared in here I think at least solving the other issue first would work best for everyone involved, as that would be a first step to eventually land, or think about, a PyDom API that makes sense.

**Closed by WebReflection** 2024-01-22 15:11 UTC
Labels: type: feature, backlog
