### ISSUE TITLE
Missing the issue templates

### ISSUE THREAD

**Issue by FahimFBA** [pyscript/pyscript#157] opened 2022-05-03 15:37 UTC
The project is currently missing the issue templates. If you would like to have some of them, then I would add a PR with some relevant issue templates. Please let me know what you think about this.

**Comment by antocuni** [comment] 2022-05-10 12:36
sorry, we didn't notice this issue and we created a duplicate one which already contains quite a bit of discussion :man_facepalming: 
Closing this as duplicate of #255

**Closed by antocuni** 2022-05-10 12:36 UTC
Labels: needs-triage
