### ISSUE TITLE
The program button event in the mobile browser cannot be executed!

### ISSUE THREAD

**Issue by ChinaGodzilla** [pyscript/pyscript#1293] opened 2023-03-19 10:14 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

··
<!DOCTYPE html>
<html lang="en" style="background: var(--bs-gray-500);">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/Login-Form-Basic-icons.css">
    <link rel="stylesheet" href="latest/pyscript.css" />
    <script defer src="latest/pyscript.js"></script>
</head>

<body style="margin-top: 118px;">
    <style type="text/css">py-splashscreen {display: none;}</style>

    <py-script>
        def Click_event():
            User_name = Element('username')
            Pass_word = Element('password')

            if str(User_name.value) == '8888' and str(Pass_word.value) == '8888':
                Show_text = Element('show')
                Show_text.write('密码正确')
                print('前端接收数据\n账号：' + User_name.value) #输出元素数值
                print('密码：' + Pass_word.value)
            elif str(User_name.value) == '' or str(Pass_word.value) == '':
                Show_text = Element('show')
                Show_text.write('账号密码未填写') #写指定元素
            else:
                Show_text = Element('show')
                Show_text.write('密码错误')
                print('前端接收数据\n账号：' + User_name.value) #输出元素数值
                print('密码：' + Pass_word.value)

            User_name.clear() #清除指定元素数据！
            Pass_word.clear()

        def Show_clear():
            Show_texe =Element('show')
            Show_texe.clear()
    </py-script>
    <section class="py-4 py-xl-5" style="background: var(--bs-gray-500);">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 style="color: var(--bs-danger);font-weight: bold;">测试登录</h2>
                    <p style="color: var(--bs-primary);">我的第一个WEB页面,测试成功账号：8888 密码：8888</p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div><input id="username" py-click="Show_clear()" type="text" style="padding-top: 6px;padding-right: 12px;padding-bottom: 6px;padding-left: 12px;border-radius: 12px;border-width: 5px;border-color: var(--bs-gray-500);min-width: 0;min-height: 0;" placeholder="账号">
                            <form class="text-center" method="post">
                                <div class="mb-3"></div>
                                <div class="mb-3"><input id="password" py-click="Show_clear()" class="form-control" type="password" name="password" placeholder="密码" style="border-radius: 12px;border-width: 5px;border-color: var(--bs-gray-500);"></div>
                                <p id="show" style="color: var(--bs-red);text-align: left;font-size: 14px;">&nbsp;</p>
                                <div class="mb-3"><button py-click="Click_event()" class="btn btn-primary d-block w-100" type="button">登录</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>·
···

My test project was built well, but I found that it can only run normally in the PC browser. In mobile browsers, button events don't work properly.

test url : https://www.sctulong.com/beta/

**Comment by FabioRosado** [comment] 2023-03-19 10:27
Hello just wanted to confirm is the button that you are testing the blue one in the login page?

I've just tested it and got the follow red text when I clicked it.

![image](https://user-images.githubusercontent.com/3131401/226169175-8755153f-92e2-4883-9d7c-d1b215a56ed3.png)

I didn't see the splash screen saying that pyscript was loading. If you disabled it, remember that you still need to wait for pyscript to finish loading before the events will be fired.

We do have some work in progress PR that improves events a bit :)

**Comment by ChinaGodzilla** [comment] 2023-03-19 10:49
@FabioRosado grateful! I just solved this problem! ! It turns out that element ID names cannot be the same as other attribute names.

**Comment by FabioRosado** [comment] 2023-03-20 09:41
Since we are improving events, i think we should do the following:
- Look to see if we get more than one element with the same ID and if the element has a `py-` attribute, if so we should raise either a warning or an error saying that events won't register due to duplicated ids.

**Comment by aneesh98** [comment] 2023-03-26 17:29
@FabioRosado , Like console.warn or console.error  or show a message on UI?

**Comment by FabioRosado** [comment] 2023-03-26 18:02
> @FabioRosado , Like console.warn or console.error  or show a message on UI?

I think we should raise a UserError which will generate an error banner automatically 😄

**Comment by aneesh98** [comment] 2023-03-27 18:53
@JeffersGlass, 
So sorry😅, I got it, thanks.

**Comment by WebReflection** [comment] 2023-03-29 09:34
should we close this or rename the issue as it's not clear to me what is it that we should do in here? thanks for clarifying

**Comment by CameronCairns** [comment] 2023-04-25 00:06
I'm attempting to debug this issue, but I'm having a hard time reproducing it as the site in question has been updated since this issue was created.  Below is my attempt to recreate the issue within a dev environment.  Leaving this here as the initial code sample does not seem to be complete.   I agree that a little more clarification may be in order, I'm not sure what the expected behavior was from the initial user.  I think the red text appearing is expected behavior, my assumption is that the issue may be linked to logging into the webserver they were hosting.

```
<!DOCTYPE html>
<html lang="en" style="background: var(--bs-gray-500);">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="https://www.sctulong.com/beta/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.sctulong.com/beta/assets/css/Login-Form-Basic-icons.css">
    <link
        rel="stylesheet"
        href="../build/pyscript.css"
    />
    <link rel="stylesheet" href="./assets/css/examples.css" />
    <script defer src="../build/pyscript.js"></script>
</head>

<body style="margin-top: 118px;">
    <style type="text/css">py-splashscreen {display: none;}</style>
<!--禁止加载动画-->
    <py-script>
        def Click_event():
            User_name = Element('username')
            Pass_word = Element('password')

            if str(User_name.value) == '8888' and str(Pass_word.value) == '8888':
                Show_text = Element('show')
                Show_text.write('密码正确')
                print('前端接收数据\n账号：' + User_name.value) #输出元素数值
                print('密码：' + Pass_word.value)
            elif str(User_name.value) == '' or str(Pass_word.value) == '':
                Show_text = Element('show')
                Show_text.write('账号密码未填写') #写指定元素
            else:
                Show_text = Element('show')
                Show_text.write('密码错误')
                print('前端接收数据\n账号：' + User_name.value) #输出元素数值
                print('密码：' + Pass_word.value)

            User_name.clear() #清除指定元素数据！
            Pass_word.clear()

        def Show_clear():
            Show_texe =Element('show')
            Show_texe.clear()
    </py-script>
    <section class="py-4 py-xl-5" style="background: var(--bs-gray-500);">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 style="color: var(--bs-danger);font-weight: bold;">测试登录</h2>
                    <p style="color: var(--bs-primary);">python编写的前端WEB页面,测试成功账号：8888 密码：8888</p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div><input id="username" py-click="Show_clear()" type="text" style="padding-top: 6px;padding-right: 12px;padding-bottom: 6px;padding-left: 12px;border-radius: 12px;border-width: 5px;border-color: var(--bs-gray-500);min-width: 0;min-height: 0;" placeholder="账号">
                            <form class="text-center" method="post">
                                <div class="mb-3"></div>
                                <div class="mb-3"><input id="password" py-click="Show_clear()" class="form-control" type="password" name="password" placeholder="密码" style="border-radius: 12px;border-width: 5px;border-color: var(--bs-gray-500);"></div>
                                <p id="show" style="color: var(--bs-red);text-align: left;font-size: 14px;">&nbsp;</p>
                                <div class="mb-3"><button py-click="Click_event()" class="btn btn-primary d-block w-100" type="button">登录</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>
```

**Comment by JeffersGlass** [comment] 2023-06-21 03:21
Since this hasn't had a response in awhile and it's unclear that there's a remaining issue, I'm going to close this for now. Feel free to reopen if it is still active/relevant.

**Closed by JeffersGlass** 2023-06-21 03:21 UTC
Labels: type: feature, good first issue, user-friendliness
