### ISSUE TITLE
error with name = input

### ISSUE THREAD

**Issue by KendallDoesCoding** [pyscript/pyscript#682] opened 2022-08-11 12:39 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

`name = input("Type your name: ")`

In the commandline, it shows Type your name and user has to input text, but using Pyscript it only shows a input box without the text, type your name.

`answer = input("Do you want to play? (y/n) ")`

Same applies for this!

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Additional Context

![image](https://user-images.githubusercontent.com/84712013/184135137-06065309-6821-460c-aa66-2a8860270578.png)

**Comment by JeffersGlass** [comment] 2022-08-11 14:59
The issue lies in how Pyodide implements input from stdin - Antocuni gives [a good overview of the issue in #239] (https://github.com/pyscript/pyscript/issues/239#issuecomment-1122366501). 

This could be considered a duplicate of that issue.

**Comment by KendallDoesCoding** [comment] 2022-08-11 15:34
> The issue lies in how Pyodide implements input from stdin - Antocuni gives [a good overview of the issue in #239] ([#239 (comment)](https://github.com/pyscript/pyscript/issues/239#issuecomment-1122366501)).
> 
> This could be considered a duplicate of that issue.

Hi, thanks for bringing to my notice.

**Closed** 2022-08-11 15:34 UTC
Labels: type: bug, needs-triage
