### ISSUE TITLE
trouble happen when using npm to install pyscript on Windows

### ISSUE THREAD

**Issue by erjiaxiao** [pyscript/pyscript#493] opened 2022-06-02 12:46 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I enter the folder “pyscript-main\pyscriptjs” , execute the command in README.md to install pyscript, and when it came to the command "npm run dev", after executing it, the trouble happened.
![1](https://user-images.githubusercontent.com/44388426/171631879-535a62b2-8bd8-478b-a0c0-ce75efdea590.png)

**Comment by marimeireles** [comment] 2022-06-02 18:30
This is just a warning @XiaoErjia, `pyscript` should be working regardless.
I remember looking into which type `loadedValues` had and I guess it was an `unknown` one, I don't really know how to fix it. Seems like it happens with [structures that fake tuples](https://github.com/Microsoft/TypeScript/issues/12707#issuecomment-398872651)? Seems like it could be fixed with a few diff. configs. to our TS config file.
If you or anyone would like to take a look at this, please! :)

**Comment by XiaoErjia** [comment] 2022-06-03 01:30
> This is just a warning @XiaoErjia, `pyscript` should be working regardless. I remember looking into which type `loadedValues` had and I guess it was an `unknown` one, but I don't really know how to fix it. Seems like it happens with [structures that fake tuples](https://github.com/Microsoft/TypeScript/issues/12707#issuecomment-398872651)? Seems like it could be fixed with a few diff. configs. to our TS config file. If you or anyone would like to take a look at this, please! :)

no, it does not works properly. after this warning, it just shows "waiting for changes" and the installation process doesn't end.
![1](https://user-images.githubusercontent.com/44388426/171769508-bd44365b-48d2-4da7-b27c-92ddc7922b89.png)

**Comment by RSMuthu** [comment] 2022-06-03 05:47
@XiaoErjia It not a bug. That's the expectation when triggered on `dev` mode with `npm run dev`
after running `npm run dev` you can use the pyscript via url `localhost:8080/build/pyscript.min.js` (you can notice the url in that console log). This dev mode is for Live reload in case we alter the pyscript code. This is very much useful when we are developing some feature or big fix on on PyScript

**Comment by XiaoErjia** [comment] 2022-06-03 05:53
> @XiaoErjia It not a bug. That's the expectation when triggered on `dev` mode with `npm run dev` after running `npm run dev` you can use the pyscript via url `localhost:8080/build/pyscript.min.js` (you can notice the url in that console log). This dev mode is for Live reload in case we alter the pyscript code. This is very much useful when we are developing some feature or big fix on on PyScript

OK I see. Thanks a lot, it does help! Now I can play with it. 
And I have fixed the warning I mentioned before, shall we open a pull request to fix it?

**Comment by marimeireles** [comment] 2022-10-04 13:49
I believe the warning was fixed? :)
If not feel free to re-open it.
Cheers, folks.

**Closed by marimeireles** 2022-10-04 13:49 UTC
Labels: tag: tooling, lang: typescript
