### ISSUE TITLE
TypeError: Promise.withResolvers is not a function

### ISSUE THREAD

**Issue by AnhTuan-AiT** [pyscript/pyscript#2011] opened 2024-03-29 01:36 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I tried some examples on the site https://pyscript.com/@examples and it really works. But when I add that sample code to my angular application, I get the error **Promise.withResolvers is not a function**, resulting in python commands not being run. 

As far as I know Promise.withResolvers is a API included in the new JS version, [starting to be supported from typescript version 5.4.0](https://github.com/microsoft/TypeScript/issues/56483). But the latest Angular version 17 is only compatible with typescript < 5.4.0, so even if I upgrade to the latest Angular version, still does not solve the issue.

Please suggest a solution to this issue. Many thanks.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
Uncaught (in promise) TypeError: Promise.withResolvers is not a function
    at Fn (custom.js:252:57)
    at define (custom.js:200:5)
    at core.js:288:13
```

**Comment by WebReflection** [comment] 2024-04-01 16:01
we polyfill that via [ungap](https://github.com/ungap/with-resolvers) and I suggest you do the same. That is included in our artifacts too so I don't understand why you have such issue. This is not a bug of this project though, it's been working with that polyfill for the last year (more or less) so I am closing this but feel free to ask more.

**Closed by WebReflection** 2024-04-01 16:01 UTC
Labels: type: bug, needs-triage

**Comment by AnhTuan-AiT** [comment] 2024-04-02 04:04
I have to add 
```typescript
import '@ungap/with-resolvers';
``` 
to my Angular component to make it works. Thank you so much for supporting.

**Comment by WebReflection** [comment] 2024-04-02 11:20
glad you solved but on the other hand `@ungap/with-resolvers` is an explicit pyscirpt dependency ... how comes your bundler didn't complain about it? 🤔
