### ISSUE TITLE
Creating a new line "\n" within an input duplicates the input line

### ISSUE THREAD

**Issue by B-Howell** [pyscript/pyscript#2147] opened 2024-08-19 20:14 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When trying to run an interactive terminal I am facing an issue of any input line with a new line character "\n" being duplicated on the terminal

```
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.8.2/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.8.2/core.js"></script>
</head>
<body>
    <script type="py" terminal worker>
        name = input("What is your name?\n")
    </script>        
</body>
```
![new_line_error](https://github.com/user-attachments/assets/f5f88cc8-20df-44f0-869b-59b4e9665e39)

I have tried multiple versions of PyScript including 2024.4.1, 2024.7.1, 2024.8.1, 2024.8.2. Any help would be greatly appreciated!

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome, Microsoft Edge

**Comment by nasrin1748** [comment] 2024-08-25 10:29
This bug looks similar to #2007

**Comment by WebReflection** [comment] 2024-08-26 10:44
Yes, it's indeed some sort of duplicate of that but the workaround is the same ... don't input with new lines, `print` instead, then ask, so this would work:

```html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.8.2/core.css">
    <script type="module" src="https://pyscript.net/releases/2024.8.2/core.js"></script>
</head>
<body>
    <script type="py" terminal worker>
        print("What is your name?")
        name = input("​")
        print(f"Hello {name}")
    </script>
</body>
```

**Please Note** there is a **zero-width** char in that input, it's not an empty string.

**Comment by WebReflection** [comment] 2024-08-26 10:46
P.S. the zero-width space can be also printed as such:

```html
    <script type="py" terminal worker>
        print("What is your name?")
        name = input("\u200b")
        print(f"Hello {name}")
    </script>
```

**Closed** 2024-08-26 10:47 UTC
Labels: type: bug, needs-triage
