### ISSUE TITLE
pyscript can't run in webbowers by using some plugins scripts,always break the fetch to pyodide,such as Tampermonkey,IDM,Adguard,uBolck or other plugins which Inject js to website.

### ISSUE THREAD

**Issue by chenchen100** [pyscript/pyscript#1148] opened 2023-02-05 02:47 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

pyscript can't run in webbowers by using some plugins scripts,always break the fetch to pyodide,such as Tampermonkey,IDM,Adguard,uBolck or other plugins which Inject js to website.
here are console logs:

`logger.ts:39 [py-splashscreen] add py-splashscreen`
`logger.ts:39 [py-terminal] No <py-terminal> found, adding one`
`logger.ts:39 [pyscript/main] Initializing runtime`
`logger.ts:39 [pyscript/pyodide] Runtime config: Object`
`logger.ts:39 [pyscript/main] Downloading pyodide-0.21.3...`
`logger.ts:39 [pyscript/main] Python startup...`
`logger.ts:39 [pyscript/pyodide] Loading pyodide    cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide_py.tar:1 `

`**Failed to load resource: net::ERR_BLOCKED_BY_CLIENT**`
`Uncaught (in promise) TypeError: Failed to fetch`
`    at loadBinaryFile (compat.ts:153:24)`
`    at loadPyodide (module.ts:115:17)`
`    at async PyodideRuntime.loadInterpreter (pyodide.ts:33:28)`
`    at async PyScriptApp.afterRuntimeLoad (main.ts:144:9)`

**in every websites which use the plugins**

### What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### Console info

```shell
}
logger.ts:39 [py-splashscreen] add py-splashscreen
logger.ts:39 [py-terminal] No <py-terminal> found, adding one
logger.ts:39 [pyscript/main] Initializing runtime
logger.ts:39 [pyscript/pyodide] Runtime config: Object
logger.ts:39 [pyscript/main] Downloading pyodide-0.21.3...
logger.ts:39 [pyscript/main] Python startup...
logger.ts:39 [pyscript/pyodide] Loading pyodide
cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide_py.tar:1 
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
compat.ts:153 
       Uncaught (in promise) TypeError: Failed to fetch
    at loadBinaryFile (compat.ts:153:24)
    at loadPyodide (module.ts:115:17)
    at async PyodideRuntime.loadInterpreter (pyodide.ts:33:28)
    at async PyScriptApp.afterRuntimeLoad (main.ts:144:9)
```

**Comment by FabioRosado** [comment] 2023-02-05 12:13
Hello @chenchen100  thank you for opening this issue with us. Just wanted to confirm, are you changing the py-config in any way?

I'm surprised to see that we tried to load the pyodide_py.tar file, does this happen with any example or with a specific pyscript project that you are working on?

**Comment by chenchen100** [comment] 2023-02-05 12:25
> 您好@chenchen100感谢您与我们一起打开此问题。只是想确认一下，您是否以任何方式更改了py配置？
> 
> 我很惊讶地看到我们试图加载pyodide_py.tar文件，这是否发生在您正在处理的任何示例或特定 pyscript 项目中？



> Hello @chenchen100 thank you for opening this issue with us. Just wanted to confirm, are you changing the py-config in any way?
> 
> I'm surprised to see that we tried to load the pyodide_py.tar file, does this happen with any example or with a specific pyscript project that you are working on?

Without modifying the configuration, I visited the example given on the official website

I also deployed the project locally and changed runtime to a native pyolide, but as I said above, this problem occurs whenever there is a browser plugin, and also on inprivate pages

**Comment by FabioRosado** [comment] 2023-02-05 12:31
> Without modifying the configuration, I visited the example given on the official website

Thank you for the clarification. I am able to run the examples in a private session, but I don't have any of the plugins you mentioned. I'll download the and comment here my findings

**Comment by chenchen100** [comment] 2023-02-05 12:31
> Hello @chenchen100 thank you for opening this issue with us. Just wanted to confirm, are you changing the py-config in any way?
> 
> I'm surprised to see that we tried to load the pyodide_py.tar file, does this happen with any example or with a specific pyscript project that you are working on?

To correct my answer, not all of it, some of it，such as adguard

**Comment by FabioRosado** [comment] 2023-02-05 15:27
I've installed adguard, ublock and tampermonkey in both firefox and Microsoft edge and I was able to run the [hello work example.](https://pyscript.net/examples/hello_world.html) as well the other examples such as repl, todo, etc.

Testing it on a private browser all seems to be working fine. Since you mention that you tested it locally and changed the configuration, can you provide your `py-config`?

**Comment by chenchen100** [comment] 2023-02-05 16:20
https://user-images.githubusercontent.com/95748110/216830546-5856c4dd-c3b6-4a28-b6a7-8028e5c0417a.mp4

if i open the plugins, it break,they are rarely successful,if I close them,pyscript works,just slowly:
![image](https://user-images.githubusercontent.com/95748110/216830592-5d138cdf-b65a-4942-a9f4-ecef14110b8f.png)


**here are my py-config:**
```
            packages = [
            "bokeh",
            "numpy"
            ]
            plugins = [
            "../build/plugins/python/py_tutor.py"
            ]

            [[fetch]]
            files = ["./utils.py", "./antigravity.py"]
            [[interpreters]]
            src = "./pyodide/pyodide.js"
            name = "pyodide-0.21.3"
            lang = "python"
```
**or just :**
```
      plugins = [
      "./build/plugins/python/py_tutor.py"
      ]
      [[fetch]]
      files = ["./antigravity.py"]
      [[interpreters]]
      src = "./pyodide/pyodide.js"
      name = "pyodide-0.21.3"
      lang = "python"
```


**repl2.html:**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>Custom REPL Example</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <link rel="stylesheet" href="repl.css" />
    <link rel="stylesheet" href="./assets/css/examples.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>
</head>

<body>
<nav class="navbar" style="background-color: #000000;">
    <div class="app-header">
        <a href="/">
            <img src="./logo.png" class="logo">
        </a>
        <a class="title" href="" style="color: #f0ab3c;">Custom REPL</a>
    </div>
</nav>
<section class="pyscript">
    <h1 class="font-semibold text-2xl ml-5">Custom REPL</h1>
<!--    [[interpreters]]-->
<!--    src = "https://cdn.bootcdn.net/ajax/libs/pyodide/0.21.3/pyodide.min.js"-->
<!--    name = "pyodide-0.21.3"-->
<!--    lang = "python"-->
    <py-tutor modules="antigravity.py">
        <py-config>
            packages = [
            "bokeh",
            "numpy"
            ]
            plugins = [
            "../build/plugins/python/py_tutor.py"
            ]

            [[fetch]]
            files = ["./utils.py", "./antigravity.py"]
            [[interpreters]]
            src = "./pyodide/pyodide.js"
            name = "pyodide-0.21.3"
            lang = "python"
        </py-config>
        <div style="margin-right: 3rem;">
            <py-repl id="my-repl" auto-generate="true"> </py-repl>
            <div id="output" class="p-4"></div>
        </div>
    </py-tutor>
</section>
</body>
</html>
```


the import js and css I use the example website file

**Comment by JeffersGlass** [comment] 2023-02-06 13:36
@chenchen100 From your original error message, the snippet `**Failed to load resource: net::ERR_BLOCKED_BY_CLIENT**` implies that one or more of the plugins is preventing Pyodide.js from loading its required resources, which include additional JS and WASM files soured from its index URL on load. 

Also, from this screenshot of your video, it appears that one or more of the plugins is downloading those files to your local disk? Pyodide assumes the resources can be sourced from the same remote index where it was sourced from, so I'm not entirely surprised it can't find them when they're instead downloaded to the hard drive.

![image](https://user-images.githubusercontent.com/1931111/216985200-cdc6f358-643a-4528-9d56-53dd64a3c58a.png)

**Comment by chenchen100** [comment] 2023-02-06 16:04
> @chenchen100从原始错误消息来看，该代码段暗示一个或多个插件阻止 Pyodide.js 加载其所需的资源，其中包括加载时从其索引 URL 中丢失的其他 JS 和 WASM 文件。`**Failed to load resource: net::ERR_BLOCKED_BY_CLIENT**`
> 
> 另外，从视频的屏幕截图来看，似乎一个或多个插件正在将这些文件下载到您的本地磁盘？Pyodide 假设资源可以来自它的来源相同的远程索引，所以我并不完全惊讶当它们被下载到硬盘驱动器时找不到它们。
> 
> ![图像](https://user-images.githubusercontent.com/1931111/216985200-cdc6f358-643a-4528-9d56-53dd64a3c58a.png)

So plugins that capture or block URLs are not compatible with PyScript? It's a bit inconvenient actually, after all, I can't always keep closing those plugins, and it is not good for useing and development too.

**Comment by JeffersGlass** [comment] 2023-02-06 16:26
>So plugins that capture or block URLs are not compatible with PyScript?

I'm not super familiar with the plugins in question, but Pyodide does need to be able to access its package index and Python source files in order to work. If the plugins are interfering with Pyodide's ability to fetch its Python source files (and install applicable packages that are built with Pyodide), then yes, that's going to cause problems.

Is there any way in these plugins you're using to whitelist a URL or subset of URLs?

**Comment by chenchen100** [comment] 2023-02-06 23:21
> 

Yes, some plugins are whitelisted, and some can only be turned off. I'm trying to find out why it was recognized as an advertisement by Adguard. Thank you for your patience ʕ ᴖᴥᴖ ʔ

**Comment by aymenBox** [comment] 2023-04-22 03:32
Hello, I'm trying to use PyScript and i had this problem today , I think this issue is caused by Pyscript itself you can't just point a CDN to pyodide_py.tar and not expect this to happen even with other download manager such as IDM wish is popular as a suggestion maybe the official website could allow us to download the pyodide_py.tar file and place it locally in the project directory as most of libraries and framework do , and for something like this to work from reading the code some logic can be changed in the pyscriptjs/src/remote_interpreter.ts script to point the packages locally in localhost, sorry for my bad English I just wanted to make a suggestion.

**Comment by chenchen100** [comment] 2023-04-22 04:44
@aymenBox FYI, I think this is related to the upstream(Pyodide) of the project. Although this issue is marked as not requiring resolution, I believe that as users increase, this issue will still arise and we need a way to solve it. 
There is currently no good solution
@JeffersGlass @FabioRosado What do you think?

**Comment by ArthurKun21** [comment] 2023-04-22 05:35
> maybe the official website could allow us to download the pyodide_py.tar file and place it locally in the project directory as most of libraries and framework do

hoping the same thing, and also seeing the browser downloading the pyodide is kinda a turn off from a user perspective

**Comment by aymenBox** [comment] 2023-04-22 12:45
@ArthurKun21 @chenchen100 i agree, from a developer perspective i have no problem with disabling My plug-in in order for it to work but in a production environment i would like to have those filles fetched from my server locally rather then to be downloaded from a CDN, i don't like to see some of my clients complaining about this issue when developing an application using it, just started to learn about it yesterday i hope the developers fix this issue as the framework looks so promising.

**Comment by chenchen100** [comment] 2023-04-22 16:16
@JeffersGlass @FabioRosado Since this issue is followed by multiple people, I will reopen this issue.

**Comment by JeffersGlass** [comment] 2023-04-22 16:37
Happy to re-open this issue - for what it's worth, quite a bit of the PyCon maintainers team is at PyCon US this weekend, so we may take a bit to actually circle back with thoughts on this issue.

**Comment by WebReflection** [comment] 2024-01-11 14:45
we have both CORS and COEP issues these days, so I am confident this specific issue from times workers were not there can be closed.

I am also a bit skeptic in closing this, due @JeffersGlass re-opening it, but I think we're past those days with workers ... Jeff feel free to re-open if this still matters, thank you!

**Closed by WebReflection** 2024-01-11 14:45 UTC
Labels: wontfix
