### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by hoodmane** [pyscript/pyscript#1343] opened 2023-03-31 19:10 UTC
`tests/integration/test_plugins.py::TestPlugin::test_pyrepl_exec_hooks` and the bokeh example are flakey.

Pyodide reruns failed tests in CI if there are a small number of them which helps with flakiness. (I think we don't have any flaky tests anymore though.)
https://github.com/pyodide/pyodide/blob/main/tools/pytest_wrapper.py

Of course it's better to fix the tests but this could be a short term solution.

**Comment by madhur-tandon** [comment] 2023-03-31 19:46
We had a lot of flaky tests for `py-repl` which were fixed with the `synclink` branch and 
`tests/integration/test_plugins.py::TestPlugin::test_pyrepl_exec_hooks` was among them as well.

Specifically, the issue with this test was that the test finished before `afterPyReplExec` could execute.
But the statement: 

https://github.com/pyscript/pyscript/blob/main/pyscriptjs/tests/integration/test_plugins.py#L274-L275

should really help with it.

Not sure why it's still flaky...

**Comment by JeffersGlass** [comment] 2023-03-31 20:52
> Not sure why it's still flaky...

This is a question of mine too - is it the test that's 'flaky', or is it that the system is behaving in a way we don't understand. That test isn't tremendously complicated, so it would be good for us to dig into exactly why it's failing and/or timing out.

**Comment by hoodmane** [comment] 2023-03-31 21:10
> is it the test that's 'flaky', or is it ...

Some pedantry:

Yes this test is flaky. A flaky test is a test that passes usually but not always. It is a symptom not a cause, so whether or not a test is flaky is trivial to observe.

Flakiness can be due to:
1. A defect in the test
2. A defect in the testing framework
3. A defect in the project
or an interaction of two or more such defects. It's often hard to diagnose.

**Comment by JeffersGlass** [comment] 2023-03-31 21:26
I can get behind that terminology! Just wanted to be sure we were all looking for root causes of the issue - I had read *"flaky test"* as "the test itself is deficient or bad", which as you've laid out is not what it means. 👍

**Comment by JeffersGlass** [comment] 2023-04-02 18:33
for `test_pyrepl_exec_hooks` - As far as I can tell, the message the console is waiting for appears in the console *before* we start to wait for it. For instance, in the console logs for one failed test run:

```
[  6.45 console.info    ] [pyscript/main] PyScript page fully initialized
[  8.57 console.log     ] beforePyReplExec called
[  8.57 console.log     ] before_src:x=2; x
[  8.57 console.log     ] before_id:pyid
[  8.58 console.log     ] afterPyReplExec called
[  8.58 console.log     ] after_src:x=2; x
[  8.58 console.log     ] after_id:pyid
[  8.58 console.log     ] result:2
```

And yet, `self.wait_for_console("result:2")` still times out.

I wonder if using `self.page.expect_console_message` directly (that is, putting `py_repl.locator("button").click()` inside that context manager, inspired by what `wait_for_console` does) would help?

**Comment by WebReflection** [comment] 2023-12-06 17:06
we don't have this issue anymore. Closing as a lot changed in the meantime.

**Closed by WebReflection** 2023-12-06 17:06 UTC
