### ISSUE TITLE
No package metadata error after installing packages

### ISSUE THREAD

**Issue by FabioRosado** [pyscript/pyscript#1204] opened 2023-02-14 11:23 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

@freakboy3742  reported this in #1203. When installing toga sometimes it would fail with "No package metadata error".

```python
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/toga/__init__.py", line 97, in _package_version
    from setuptools_scm import get_version
ModuleNotFoundError: No module named 'setuptools_scm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 435, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 304, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 2, in <module>
  File "/lib/python3.10/runpy.py", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lib/python3.10/site-packages/freedom/__main__.py", line 1, in <module>
    from freedom.app import main
  File "/lib/python3.10/site-packages/freedom/app.py", line 1, in <module>
    import toga
  File "/lib/python3.10/site-packages/toga/__init__.py", line 118, in <module>
    __version__ = _package_version(__file__, __name__)
  File "/lib/python3.10/site-packages/toga/__init__.py", line 115, in _package_version
    return importlib_metadata.version(package)
  File "/lib/python3.10/importlib/metadata/__init__.py", line 955, in version
    return distribution(distribution_name).version
  File "/lib/python3.10/importlib/metadata/__init__.py", line 928, in distribution
    return Distribution.from_name(distribution_name)
  File "/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for toga-core
```

I'm opening this issue for us to dig more into this since I have seen the same error happening before a couple times and was trying to help a user with this issue.

So far the error seems occur at random. It's not clear to me if this is happening with a recent change that we have done or if it was always present but we didn't see the error 🤔

**Comment by freakboy3742** [comment] 2023-02-14 23:21
Providing some diagnostic details: I've seen this myself on macOS Monterey (on an M1), on both Safari and Chrome. We've had other reports (beeware/briefcase#1089) on Linux (PopOS) with Chrome and Firefox.

**Comment by hoodmane** [comment] 2023-02-26 06:53
This looks like a probable Pyodide bug. Can it be reproduced in Pyodide?

**Comment by freakboy3742** [comment] 2023-02-26 06:56
It seems likely - however, as I indicated on the original ticket, I haven't had any luck reducing the problem to a simpler case that doesn't involve Briefcase, Toga, and Pyscript.

I suspect a reproduction case will involve importing a wheel (or wheels?) from a file being served on the same domain as is serving the page, and requesting importlib metadata for one of those wheels very soon after the import is made.

**Comment by hoodmane** [comment] 2023-02-26 07:00
Can you upload a zip archive with a complete reproduction. Doesn't have to be minimal, minimizing intermittent errors can drive one mad. I would appreciate it if you make a reasonable effort to reduce it.

Things that might help make reproduction more consistent: 
* Open devtools network tab and check the "disable cache" box
* run in incognito mode

**Comment by freakboy3742** [comment] 2023-02-26 07:05
[This project](https://github.com/pyscript/pyscript/tree/main/examples/toga) is a reproduction case; serving `freedom.html` with a web server that can access `./static` is sufficient.

I've tried to reduce it further; but every reduction I've made ends up making the problem go away.

**Comment by hoodmane** [comment] 2023-02-26 07:10
Doing this I get `Loading failed for the <script> with source “http://localhost:8000/build/pyscript.js”.`. Please provide complete instructions for the reproduction.

**Comment by freakboy3742** [comment] 2023-02-26 07:17
Not sure where that error is coming from; complete instructions are:
```
git clone https://github.com/pyscript/pyscript.git
cd pyscript/examples/toga 
python3 -m http.server
```
then open a browser at http://127.0.0.1:8000/freedom.html

**Comment by hoodmane** [comment] 2023-02-26 07:23
I cannot reproduce the error. I see the following:
<img width="752" alt="Screenshot 2023-02-26 at 7 22 38 AM" src="https://user-images.githubusercontent.com/8739626/221397712-a97344de-3fcb-41c7-9595-f0630faca496.png">

**Comment by hoodmane** [comment] 2023-02-26 07:23
Do I need to use an old commit of pyscript?

**Comment by freakboy3742** [comment] 2023-02-26 07:32
This is on e2c24592907ad5c14f15085461910d3adbe3fa9b (which is the latest commit) in the repo. This has me well confused... I can't work out where a "build" path is coming from - there's nothing in `freedom.html` that references `build`.

There's a reference to a "build" folder in pyscript `https://pyscript.net/latest/pyscript.js` ... but not `build/pyscript.js`.

**Comment by hoodmane** [comment] 2023-02-26 07:40
Okay I cloned a fresh copy of the repo and now the page loads as expected. I'm not sure what I was doing wrong before though, git status shows it was clean and on main... Anyways I don't see the error still. Should I just refresh a bunch?

**Comment by hoodmane** [comment] 2023-02-26 07:41
Okay in incognito mode I get the error. Great!

**Comment by freakboy3742** [comment] 2023-02-26 07:42
The reproducibility is the fun part :-) Some users apparently have no problem at all; but I get it reliably 3 out of 5 loads. Reloading the page a few times is usually all it takes. I haven't noticed any particular pattern in OS/versions/browser in the problem cases.

**Comment by hoodmane** [comment] 2023-02-26 07:55
I suspect this issue is fixed in Pyodide 22. Try adding:
```
[[runtimes]]
src = "https://cdn.jsdelivr.net/pyodide/v0.22.1/full/pyodide.js"
```
and let me know if you can still reproduce.

**Comment by hoodmane** [comment] 2023-02-26 08:02
I think this was due to https://github.com/pyodide/pyodide/issues/3311, fixed in https://github.com/emscripten-core/emscripten/pull/18301.

**Comment by freakboy3742** [comment] 2023-02-26 08:08
It certainly looks like that might have fixed it - I haven't had an error in a dozen reloads. Thanks!

**Comment by freakboy3742** [comment] 2023-02-26 23:26
FWIW - I'm happy to call this one closed; it sounds like @FabioRosado may have other manifestations of this bug that he's tracking, so I'll leave it to him to close the ticket if/when he's happy.

**Comment by hoodmane** [comment] 2023-02-27 00:35
+1 for closing this issue.

**Comment by FabioRosado** [comment] 2023-02-27 10:13
Yeah I think we are good to close this thank you for looking into this 😄

We have also updated pyscript to use the latest version of pyodide so when we release this issue will be fixed 👍

**Closed** 2023-02-27 10:14 UTC
Labels: type: bug
