### ISSUE TITLE
display() appending an <img> as a child of an existing <img> when append=False, for a png

### ISSUE THREAD

**Issue by machallboyd** [pyscript/pyscript#1150] opened 2023-02-05 23:47 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

While attempting the [Getting Started](https://github.com/machallboyd/pyscript/blob/main/docs/tutorials/getting-started.md) tutorial, found that the final step didn't behave as expected, as the graph didn't update on radio button click. On examination, it seems that the new `<img>` created by the `plot` handler is a child of the existing `<img>` element, rather than replacing it.  

This seems similar to existing closed issue https://github.com/pyscript/pyscript/issues/1123, but for png instead of svg

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by FabioRosado** [comment] 2023-02-06 10:04
Hello @machallboyd  thank you for opening this issue with us. I've just tested the get started with the unstable release (main) and confirmed that the graph now updates. Unfortuntely, we will need to wait for a release for this to be fixed with #1123

I'm closing this issue since #1126 fixes the issue for both svg and anything inside an `<img>` tag 😄 

Please let us know if you need help with anything else!

**Closed by FabioRosado** 2023-02-06 10:04 UTC
Labels: type: bug, needs-triage
