### ISSUE TITLE
Passing elements to pyscript.when causes ImportError in MicroPython

### ISSUE THREAD

**Issue by kkinder** [pyscript/pyscript#2062] opened 2024-05-15 12:41 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

It seems that although you guys support `pyscript.when` with Micropython, it does not support passing a non-string element. For example:

```python
from js import window
from pyscript import when

@when("popstate", window)
def on_popstate(event):
    pass
```

This results in an ImportError:

```
  File "pyscript/event_handling.py", line 27, in decorator
ImportError: no module named 'pyweb'
```

I took a look at [the relevant file](https://github.com/pyscript/pyscript/blob/e7216d26e755fe85f29ceccad29e2da63a11ac1c/pyscript.core/src/stdlib/pyscript/event_handling.py#L25C1-L28C1) and it looks like there's a logic fork for non-string selectors on when, which isn't supported in Micropython.

The docs don't make that clear, however.

### Console info

```shell
PythonError: Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "x/application.py", line 10, in <module>
  File "x/application.py", line 45, in Application
  File "pyscript/event_handling.py", line 27, in decorator
ImportError: no module named 'pyweb'
```
```


### Additional Context

_No response_

**Comment by WebReflection** [comment] 2024-11-04 15:20
late reply, my apologies, but what's that `from js import window` about? in here, it's usually `from pyscript import window` so that you always know that's the `window` you are after. Do you mind expanding on the test case?

**Comment by WebReflection** [comment] 2024-11-18 14:20
the `@when` decorator is under heavy-lifting but also there was no reply around this issue, or follow up, in a while ... closing as currently likely irrelevant, as we also changed tests to run these on MicroPython too and the `@when` decorator works just fine in there. Feel free to re-open if after our latest changes the issue is still there, thank you.

**Closed by WebReflection** 2024-11-18 14:20 UTC
Labels: type: bug, needs-triage
