### ISSUE TITLE
JS TypeError triggered by PyButton.connectedCallback

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#673] opened 2022-08-09 13:32 UTC
This is a bug which was discovered while developing #663 .
If you try to execute `TestPyButton.test_on_click`:
https://github.com/pyscript/pyscript/blob/3d372f797658eb4e914682563bb75ba10b131d7e/pyscriptjs/tests/test_py_button.py#L6-L34

You notice that it raises the following JS exception:
```
base.ts:191 Uncaught TypeError: Cannot use 'in' operator to search for 'runPythonAsync' in undefined
    at base.ts:191:33
    at Object.subscribe (index.mjs:50:9)
    at PyButton.runAfterRuntimeInitialized (base.ts:190:23)
    at PyButton.connectedCallback (pybutton.ts:68:14)
    at main.ts:20:34
    at main.ts:38:25
```

I didn't investigate further, but it seems something which should be fixed.

~Assuming that #663 will be merged soon, once this issue is fixed we also need to remove the `@pytest.mark.xfail` decorator from the test.~

**EDIT:** #663 was merged, and #676 found another test which fails because of this:
https://github.com/pyscript/pyscript/blob/c308b0679d924a6a4ccdc7b5131f9a28fa0d14ef/pyscriptjs/tests/test_zz_examples.py#L185-L191

In order to properly fix this issue, a PR should:

- add a new test minimal test (e.g. in test_01_basic.py) which showcases the problem
- fix the bug :)
- remove the `@pytest.mark.xfail` from the two tests mentioned above and ensure that they pass

**Comment by FabioRosado** [comment] 2022-08-21 15:08
This issue popped up when working on adding more tests, I didn't do much digging but it seems that `runAfterRuntimeInitialized` is called with an undefined value :thinking:  

I've tried to add an assert and this seems to fix the issue and doesn't seem to cause any breaking:


```typescript
    runAfterRuntimeInitialized(callback: () => Promise<void>){
        pyodideLoaded.subscribe(value => {
            if ('value && runPythonAsync' in value) {
                setTimeout(async () => {
                    await callback();
                }, 100);
            }
        });
    }
```

I'm still slightly concerned as to why the value was undefined. I'm planning to spend some more time and look into this to try and figure out what's happened here :thinking:

**Comment by FabioRosado** [comment] 2022-08-30 10:20
Apologies for the ping @fpliger  and Antonio, I've finally spent a bit more time looking into this. I'm starting to suspect this might be a race condition between running the tests and waiting for pyodide to load.

I'll share my debugging with you, hopefully its useful :smile: 


## Debugging

Since we are capturing the console logs when we run the tests (thanks Antonio!), it's easier to see what is happening. Here are the logs:

```
[  0.00 page.goto      ] on_click.html
[  0.02 http_server    ] "GET /on_click.html HTTP/1.1" 200 -
[  0.03 http_server    ] "GET /build/pyscript.css HTTP/1.1" 200 -
[  0.03 http_server    ] "GET /build/pyscript.js HTTP/1.1" 200 -
[  0.13 console.log    ] adding initializer async function mountElements() {
        console.log('Collecting nodes to be mounted into python namespace...');
        const matches = document.querySelectorAll('[py-mount]');
        let source = '';
        for (const el of matches) {
            const mountName = el.getAttribute('py-mount') || el.id.split('-').join('_');
            source += `\n${mountName} = Element("${el.id}")`;
        }
        await runtime$1.run(source);
    }
[  0.13 console.log    ] added initializer async function mountElements() {
        console.log('Collecting nodes to be mounted into python namespace...');
        const matches = document.querySelectorAll('[py-mount]');
        let source = '';
        for (const el of matches) {
            const mountName = el.getAttribute('py-mount') || el.id.split('-').join('_');
            source += `\n${mountName} = Element("${el.id}")`;
        }
        await runtime$1.run(source);
    }
[  0.13 console.log    ] adding post initializer async function initHandlers() {
        console.log('Collecting nodes...');
        for (const pyAttribute of pyAttributeToEvent.keys()) {
            await createElementsWithEventListeners(runtime$1, pyAttribute);
        }
    }
[  0.13 console.log    ] added post initializer async function initHandlers() {
        console.log('Collecting nodes...');
        for (const pyAttribute of pyAttributeToEvent.keys()) {
            await createElementsWithEventListeners(runtime$1, pyAttribute);
        }
    }
[  0.15 console.log    ] RUNTIME READY
[  0.15 console.log    ] initializers set
[  0.15 console.log    ] post initializers set
[  0.15 console.log    ] scripts queue set
[  0.15 console.log    ] config set!
[  0.15 JS exception   ] TypeError: Cannot use 'in' operator to search for 'run' in undefined
    at http://127.0.0.1:8080/build/pyscript.js:350:27
    at Object.subscribe (http://127.0.0.1:8080/build/pyscript.js:61:13)
    at PyButton.runAfterRuntimeInitialized (http://127.0.0.1:8080/build/pyscript.js:349:27)
    at PyButton.connectedCallback (http://127.0.0.1:8080/build/pyscript.js:26883:18)
    at http://127.0.0.1:8080/build/pyscript.js:27221:20
    at http://127.0.0.1:8080/build/pyscript.js:27283:3
[  0.15 console.log    ] config set!
[  0.16 console.log    ] config set {autoclose_loader: true, runtimes: Array(1)}
[  0.16 console.log    ] Initializing runtimes...
[  0.22 console.log    ] creating pyodide runtime
[  1.35 console.log    ] Python initialization complete
[  1.35 console.log    ] loading micropip
[  1.35 console.log    ] Loading micropip, pyparsing, packaging, distutils
[  1.44 console.log    ] Loaded micropip, packaging, distutils, pyparsing
[  1.44 console.log    ] loading pyscript...
[  1.91 console.log    ] done setting up environment
[  1.91 console.log    ] RUNTIME READY
[  1.91 console.log    ] Collecting nodes to be mounted into python namespace...
[  1.92 console.log    ] scripts queue set
[  1.92 console.log    ] ------ loader closed ------
[  1.92 console.log    ] Collecting nodes...
[  1.92 console.log    ] ===PyScript page fully initialized===
```
I was too focus on the failure itself and didn't spent much time looking at these properly, that was a mistake. Following the code, it seems that we load the initializers, then pyenv runs and logs `RUNTIME READY`, then the post initializers and finally set the config. 

So far so good, but then things blow up.

Following the logs, it seems that our `runAfterRuntimeInitialized` is being called immediately after the config is set. After adding a small log error, I confirmed that `PyButton` runs after the config is set. 


### Runtime ready message

I was curious to see what the runtime was for that first log message, so I added a bunch of logs to the `pyenv.ts`

```ts
runtimeLoaded.subscribe(value => {
    console.error(value);
    runtime = value;
    console.log('RUNTIME READY');
});
console.error(runtime);
```

This might not be a surprise, but both runtime and value are `undefined`, just to see what would happen I've added the following code to `base.ts`

```ts
if (!runtime) {
    runtime = new PyodideRuntime();
    runtime.initialize();

    runtimeLoaded.set(runtime);
} else {
    runtimeLoaded.subscribe(value => {
        runtime = value;
    });
}
```

Then running the tests the pybutton test passes! But the PyRepl tests now seem broken, the simple clock demo also seems a bit broken:

```
start time:
08/30/2022, 11:07:21
08/30/2022, 11:07:21
08/30/2022, 11:14:44
```

## Fixing the unit tests

The unit test can be fixed by initializing the runtime first (I stole this idea from @madhur-tandon runtime tests):

```ts
    let runtime: PyodideRuntime;
    beforeAll(async () => {
        runtime = new PyodideRuntime();
        await runtime.initialize();
    });
```

After running the pybutton unit tests, the test where we are asserting the error 'TypeError: Cannot use 'in' operator to search for 'runPythonAsync' in undefined' fails because the test doesn't trigger this error anymore :tada: 

Hopefully this is helpful, let me know if you have any ideas that you can point me to see if we can fix this issue :smile:

**Comment by fpliger** [comment] 2022-08-30 21:39
Great catch/analysis @FabioRosado ! This is super helpful

Yeah, it's likely that you are correct. Code is being called too early and the runtime is not initialized yet. I'd suggest checking also that `value` is not `undefined` so we only set `runtime` when `value` it's actually a valid  `runtime`.

**Comment by antocuni** [comment] 2022-09-07 09:17
Thank you @FabioRosado , I agree that it's super helpful, and your analysis convinced me once more that we need to come up with a better design for the whole lify cycle of a page, including the interactions between the various components and make clear "who calls what".

In the meantime, I just wanted to comment on this:

> This might not be a surprise, but both runtime and value are `undefined`, just to see what would happen I've added the following code to `base.ts`

it was definitely a surprise for me, but it turns out to be an intended behavior of svelte stores:
https://stackoverflow.com/a/66819321

**Closed** 2022-09-13 14:59 UTC
Labels: type: bug, lang: typescript
