### ISSUE TITLE
Page goes on infinite loop when using pys-onClick

### ISSUE THREAD

**Issue by programmatismos** [pyscript/pyscript#1068] opened 2022-12-23 19:56 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

![Screenshot_20221223_095436](https://user-images.githubusercontent.com/121314793/209400433-82329492-912a-4840-8bcd-9e3bc678e44c.png)

### Additional Context

I used this code:

```
<input type="text" id="test-input" />
<button id="submit-button" type="submit" pys-onClick="myFunc">OK</button>
<div id="test-output"></div>

<py-script>
from js import console

def myFunc(*args, **kwargs):
    text = Element('test-input').element.value
Element('test-output').element.innerText = text

</py-script>
```

**Comment by FabioRosado** [comment] 2022-12-23 20:58
Hello @programmatismos thank you for raising this issue.

It seems that the problem is that your last `Element` is trying to use `text` but that is being defined in the function body whilst the Element isn't.

It also seems we need to improve things such as closing the loader screen if there's any python exception

**Comment by FabioRosado** [comment] 2022-12-23 21:10
Just an update, I was going to write some texts to fix this usse, but yes, it seems that yes, the issue of the splashscreen not closing is indeed using `pys-onClick`, if you use `py-click` the splashscreen seems to close as expected and you can see the error message.

**Comment by programmatismos** [comment] 2022-12-23 21:11
Hi @FabioRosado! Thanks for the quick response!

Even when I make the text global it still loads infinitely.

Any ideas?

**Comment by FabioRosado** [comment] 2022-12-23 21:12
Can you replace `pys-onClick` with `py-click`? The `pys-onClick` is deprecated and eventually will be removed.

**Comment by programmatismos** [comment] 2022-12-23 21:19
By replacing `pys-onClick` with `py-click` got away from infinite loop but the output is not showing.

My code:
```
<input type="text" id="test-input" />
<button id="submit-button" type="submit" py-click="myFunc">OK</button>
<div id="test-output"></div>

<py-script>
def myFunc(*args, **kwargs):
    global text
    text = Element('test-input').element.value
    Element('test-output').element.innerText = text

</py-script>
```

**Comment by FabioRosado** [comment] 2022-12-23 21:43
Just tested this and you need to replace `py-click="myFunc"` with `py-click="myFunc()` that way the function is called when the user clicks the button.

Here's the working code:

```html
<input type="text" id="test-input" />
<button id="submit-button" type="submit" py-click="myFunc()">OK</button>
<div id="test-output"></div>

<py-script>
def myFunc(*args, **kwargs):
    global text
    text = Element('test-input').element.value
    Element('test-output').element.innerText = text

</py-script>
```

**Comment by programmatismos** [comment] 2022-12-23 21:47
Thanks a lot @FabioRosado ! It worked! :)
Please consider putting this on Documentation as I found about `py-click` from a YT video I think.

PyScript rocks!

**Comment by FabioRosado** [comment] 2022-12-23 21:51
Glad it worked!

Yeah we starting improving the documentation a bit, but there is still much to do 😄 
I'll create a tutorial on how to use the py-click attributes following your suggestion 😄

**Closed** 2022-12-30 12:34 UTC
Labels: type: bug, needs-triage
