### ISSUE TITLE
antigravity demo does not work

### ISSUE THREAD

**Issue by pleabargain** [pyscript/pyscript#217] opened 2022-05-05 06:41 UTC
video
https://youtu.be/-6clz5M504U

referencing pyscript from the web

partial error
```
Exception has occurred: PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
```

**Comment by antocuni** [comment] 2022-05-06 13:13
The problem is that VS Code opens the file directly from the filesystem. If you serve the file from a webserver (either in production or a local development webserver) the example work.

Duplicate of https://github.com/pyscript/pyscript/issues/257, which explains better the issue and shows a workaround.

**Closed by antocuni** 2022-05-06 13:13 UTC
Labels: needs-triage
