### ISSUE TITLE
Can not load .py files on the file system

### ISSUE THREAD

**Issue by vaibhavgarg1982** [pyscript/pyscript#209] opened 2022-05-05 03:18 UTC
Attempting to access any .py file from within the HTML page fails. The error shown in console is as under: 

`Access to fetch at 'file:///C:/data.py' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.`

For reference, I am running this on Windows 11, over Edge-Chromium. Also, in lining the code works as expected.

**Comment by work-ruchir** [comment] 2022-05-05 04:51
Try running your page on a server (live server, http server). Live server can directly be installed from VSCODE marketplace.

**Comment by antocuni** [comment] 2022-05-06 13:26
Duplicate of #179

**Closed by antocuni** 2022-05-06 13:26 UTC

**Comment by marimeireles** [comment] 2022-09-08 11:22
Tracked on #756
