### ISSUE TITLE
input() no work propah

### ISSUE THREAD

**Issue by Acalann** [pyscript/pyscript#628] opened 2022-07-24 20:59 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When you put the string thing in the brackets it should print that then ask for input, but here it does the opposite, it asks for input with blank message, then after input is done it shows text.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
No errors
```

**Comment by JeffersGlass** [comment] 2022-07-25 14:09
There is discussion and possible improvements to fix this in #239 - believe this can be considered a duplicate of that issue.

**Comment by ntoll** [comment] 2022-07-26 13:06
Will mark as a duplicate and close. Please continue discussion in #239.

**Closed by ntoll** 2022-07-26 13:06 UTC
Labels: type: bug, needs-triage
