### ISSUE TITLE
[BUG] I can't use it now... It was working yesterday.

### ISSUE THREAD

**Issue by xX7912Xx** [pyscript/pyscript#429] opened 2022-05-19 16:31 UTC
link: http://www.dotcs.community/PyScript/DCSSDP.html

I didn't change my .html file.

Here are some screenshots:
2022.05.15:
![0CG7`J9%LG11E1K81@HH_@1](https://user-images.githubusercontent.com/60053890/169353531-009b4c3a-7e3e-4dc2-bf9c-1f0e664490e9.jpg)
![26UQK3TS2%~Z~CSN$9UM6@R](https://user-images.githubusercontent.com/60053890/169353439-162a1faa-026c-46d9-ae0a-e5c99968193e.jpg)

Now:
![image](https://user-images.githubusercontent.com/60053890/169351785-588695d0-3cd7-4f63-b815-3f0c4f0b2fb0.png)![image](https://user-images.githubusercontent.com/60053890/169351656-d9e53262-f13f-44a5-8904-54a10fde60f4.png)
![image](https://user-images.githubusercontent.com/60053890/169351837-15fbe876-875c-4f1a-b8e4-2b50dfcb25f3.png)

**Comment by siddhi** [comment] 2022-05-19 16:47
Duplicate of #427

**Comment by marimeireles** [comment] 2022-05-19 16:48
Yes, please check the comment on how to build it locally =)
We're working right now to fix it!

**Closed by marimeireles** 2022-05-19 16:48 UTC
Labels: needs-triage

**Comment by xX7912Xx** [comment] 2022-05-19 16:49
> 

OK, thanks.
