### ISSUE TITLE
rich terminal broken in 2024.2.1+ 

### ISSUE THREAD

**Issue by Didymograptus** [pyscript/pyscript#2002] opened 2024-03-20 12:43 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

In 2024.1.1 this works (yellow 'Hello world!' in the terminal):

toml:
``` toml
packages = ["colorama", "rich"]
```
main.py:
``` Python
from colorama import Fore, Back, Style
from rich.console import Console
console = Console()

console.print(f"{Fore.YELLOW}Hello world!")
```
However from 2024.2.1 and 2024.3.1 this is broken and the following is printed:
```
[33mHello world!
```

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
No errors in the console
```

**Comment by WebReflection** [comment] 2024-03-21 15:04
I think we changed pretty much nothing there between 2024.2.1 and 2024.3.1 around the terminal so maybe this is an upstream XTerm issue ... by any chance you checked in there if this is a known issue around latest changes? Thank you!

**Comment by JeffersGlass** [comment] 2024-04-04 11:45
I can confirm I'm seeing this issue too - doing a bisect, it looks like this was broken by #1941. 

After some experimentation, and research, it seems like xterm.js is not generically a TTY. At least, making both of the `generic` type outputs to xterm.js `isatty = False` resolves this. Have not looked to much into what the knockon effects might be.

**Comment by WebReflection** [comment] 2024-04-04 13:08
uhm ... `isatty` is rather for Pyodide than XTerm but indeed if XTerm is not `tty` then it was my bad assuming it was ... I have refactored the whole terminal thing to fix MicroPython issues and to be honest in MicroPython I don't care about *tty* or not, I've manually implemented the thing by my own.

I will try to see if forcing `isatty` to `false` causes any other issue but if not, I think we can bring that into this MR https://github.com/pyscript/pyscript/pull/2014

**Comment by WebReflection** [comment] 2024-04-04 13:18
P.S. worth noticing that MicroPython also works without issues, see:

```python
print("\x1b[1mHello World\x1b[0m !!!")
```

**Comment by WebReflection** [comment] 2024-04-04 13:34
it's in, will be working as expected in 2024.4.1 👋

**Closed** 2024-04-04 13:33 UTC
Labels: type: bug, needs-triage
