### ISSUE TITLE
IDM trying to download pyodide_py.tar file

### ISSUE THREAD

**Issue by karan-khatri** [pyscript/pyscript#261] opened 2022-05-06 14:45 UTC
The Internet download manager extension tries to download the pyodide.tar file instead of loading it to the python environment and due to that, the execution is stopped leaving a bunch of errors in the browser console.

**Comment by karan-khatri** [comment] 2022-05-06 14:52
Here is the screenshot that may help.

![image](https://user-images.githubusercontent.com/84270645/167157637-4889e6c5-9e93-40f7-81e4-aeeb197d1065.png)

**Comment by rahim0004** [comment] 2022-05-06 16:26
> The Internet download manager extension tries to download the pyodide.tar file instead of loading it to the python environment and due to that, the execution is stopped leaving a bunch of errors in the browser console.

That is also happening to me . It only happens when your code has some errors like indentation etc. Disable IDM extension to see those errors on the web page.

**Comment by Nelsonwin** [comment] 2022-05-16 18:58
Disabling the IDM extension worked for me.

**Comment by marimeireles** [comment] 2022-06-03 14:09
Seems like they're doing the wrong thing trying to download any `.tar` files available?
Seems extremely dangerous also. Can someone confirm this happens with other `.tar`s? Or just ours?

If it ours only might be a server configuration issue and I can ping the right person to fix it.

Thanks!

**Comment by dilshankarunarathne** [comment] 2022-06-22 08:29
I have the same issue. I could just disable the IDM extension, but shouldn't it be fixed?

**Comment by AmirAliAy** [comment] 2022-07-05 12:43
I have this problem and it just show loading runtime

**Comment by karan-khatri** [comment] 2022-08-14 10:04
IDM does try to grab all the .tar files that are requested by the browser from any site.
I think you should do some configuration so that IDM is not able to grab the tar file from your server.
When I removed .tar extension from the list of extensions of files the IDM tries to grab, the <py-script> worked perfectly.

**Comment by karan-khatri** [comment] 2022-08-14 10:11
> Seems like they're doing the wrong thing trying to download any `.tar` files available? Seems extremely dangerous also. Can someone confirm this happens with other `.tar`s? Or just ours?
> 
> If it ours only might be a server configuration issue and I can ping the right person to fix it.
> 
> Thanks!


This is the list of extensions from which I removed the .TAR extension and everything worked smoothly. 
The problem is that doing so will disable me from downloading tar files from every website.

**Comment by Binyoh1** [comment] 2022-09-11 17:10
An alternative I used was adding the CDN address of the pyodide file (in this case: **https://cd.jsdeliver.net/pyodide/v0.20.0/full/pyodide_py.tar**) to the list of address exceptions in IDM under options, then navigating to the **File types** bar
![Screenshot (16)](https://user-images.githubusercontent.com/102781849/189540173-28dc72ef-437c-429a-9e8a-4d0d041da570.png)

This way, you don't have to disable the IDM extension in any browser.

**Comment by karan-khatri** [comment] 2022-09-14 09:59
> 

Yeah, that one is a good idea!

**Comment by karan-khatri** [comment] 2022-09-14 10:00
> An alternative I used was adding the CDN address of the pyodide file (in this case: **https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide_py.tar**) to the list of address exceptions in IDM under **Options**, then navigating to the **File types** bar. This way, you don't have to disable the IDM extension in any browser or remove the **.TAR** file extension altogether.
> 
> ![Screenshot (16)](https://user-images.githubusercontent.com/102781849/189540173-28dc72ef-437c-429a-9e8a-4d0d041da570.png)
> 
> ![Screenshot (17)](https://user-images.githubusercontent.com/102781849/189540396-330a11bf-a5c7-451b-92a0-56d5a887f799.png)

Yeah, That's a good idea.

**Comment by marimeireles** [comment] 2022-09-29 14:31
I guess I'm closing this as completed?
Not sure if we can do anything on our side?
I might be wrong, if you anyone thinks we can do something on our side please re-open it!
Thanks for posting this workaround @karan-khatri. Cheers!

**Closed by marimeireles** 2022-09-29 14:31 UTC
Labels: waiting on reporter, tag: tooling

**Comment by ArthurKun21** [comment] 2023-04-19 06:37
is there no way that pyscript could not let itself be download by IDM? 

so that users wouldn't need to know the workaround and just use it as is?

**Comment by aymenBox** [comment] 2023-04-22 03:11
Hello, I'm trying to use PyScript and i had this problem today , I think this issue is caused by Pyscript itself you can't just point a CDN to `pyodide_py.tar` and not expect this to happen even with other download manager such as **IDM wish is popular** as a suggestion maybe the official website could allow us to download the **pyodide_py.tar** file and place it locally in the project directory as most of libraries and framework do , and for something like this to work from reading the code some logic can be changed in the` pyscriptjs/src/remote_interpreter.ts` script to point the packages locally in localhost, sorry for my bad English I just wanted to make a suggestion.

**Comment by WebReflection** [comment] 2023-04-24 08:22
I agree with @marimeireles here there's not much we can do:
  * we don't control jsDelivr end points
  * we don't have anything to do with IDM browser extension (and more extensions might cause the same issue)

However, the explicit CDN hack/workaround doesn't look good to me, because that'll always be behind latest *pyodide* and asking users to maintain versioning on their own doesn't look good to me ...

Accordingly, I suggest three alternatives (plus eventually us writing about this on our README somewhere):
  1. instead of `https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide_py.tar` use `https://cdn.jsdelivr.net/pyodide/*/*/pyodide_py.tar` so that versioning wouldn't matter and there is enough specificity of the file that should not be download
  2. we feature-detect broken `.tar` downloads on our side and inform users how to allow *pyodide*
  3. publish `pyodide_py.tar` as `pyodide_py.tar.blob` instead, but I need @hoodmane here to understand if that's a good idea at all

**Comment by hoodmane** [comment] 2023-04-24 14:40
On Pyodide 0.23 we moved to using`python_stdlib.zip`. 

We aren't really interested in constraining file names in our distro. Tons of tools we use all the time care that files have the correct file extension. Some tools we never use want them to have the wrong extension. What about wheels downloaded from pypi? We can't upload weird file extensions to pypi.

Browser extensions sometimes break websites. When that happens the user has to turn them off or not use the website.

**Comment by hoodmane** [comment] 2023-04-24 14:55
If someone wishes to they are welcome to maintain the equivalent of [pyodide-webpack-plugin(https://github.com/pyodide/pyodide-webpack-plugin) but for internet download manager

**Comment by WebReflection** [comment] 2023-04-24 15:10
> On Pyodide 0.23 we moved to usingpython_stdlib.zip.

hah, so the exception should be `https://cdn.jsdelivr.net/pyodide/*/*/pyodide_py.*` instead, which is even better.

Agreed with the rest, it feels like an extension issue or its lack of sane defaults for popular libraries and their possible CDN dependencies.
