### ISSUE TITLE
HTML not getting rendered everytime.

### ISSUE THREAD

**Issue by kumargautam99** [pyscript/pyscript#370] opened 2022-05-14 06:11 UTC
I tried the sample script for computing the value of pi.

Using the CDN url of pyscript.js and pyscript.css , 80% of the times the render is happening after Loading runtime... 
But sometimes it gives the pink color section as output and no content.

Using the pyscript.js and pyscript.css locally, the Loading runtime.. persists for minutes without any output.
<img width="800" alt="render_issue" src="https://user-images.githubusercontent.com/12942825/168413317-c5d2d67e-6c81-4050-8af9-91e1deb68b6b.PNG">

**Comment by rayjolt** [comment] 2022-05-14 06:31
I am seeing this issue as well, with the following HTML document:

```html
<html>
  <head>
    <title>PyScript Test</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body>
    <py-script>
print("Testing PyScript")
    </py-script>
  </body>
</html>
```

Looking at the console, I see the following error:

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "<exec>", line 164, in write
  File "<exec>", line 116, in write
JsException: SyntaxError: Document.querySelector: '#-2cfe72dd-aed7-7bb3-50f0-d5a53fa5d0ab' is not a valid selector
    PythonError error_handling.gen.ts:309
    new_error pyodide.asm.js:14
    callPyObjectKwargs pyproxy.gen.ts:374
    callKwargs pyproxy.gen.ts:1167
    evaluate base.ts:115
error_handling.gen.ts:309:4
```

This error occurred 5 times out of 10 when I tested it.
Tested on Firefox 100.0, Ubuntu 20.04 LTS.

Looks like there is some kind of race condition when writing to stdout.

**Comment by marianoweber** [comment] 2022-05-14 08:10
This seems to be a problem with the CDN build. 
With the build from the CDN, I can reproduce it. Locally built from the source, I can't.

**Comment by pauleveritt** [comment] 2022-05-14 21:04
There's a discussion in #359

**Comment by yannickfunk** [comment] 2022-05-14 21:18
@pauleveritt I think the issue here is a different issue than #359

**Comment by yannickfunk** [comment] 2022-05-14 22:48
I think the problem here is that `this.constructor.name` breaks in minified code.

> There is [name property](http://stackoverflow.com/questions/29310530/get-the-class-name-of-es6-class-instance) that already exists in regular functions class constructors. A known pitfall is that it will be mangled in minified code, so it is generally useless in browser JS, and its use can be considered an antipattern. name cannot be reassigned (in some browsers), so a separate property is needed to identify the class.

(https://stackoverflow.com/questions/46217853/get-constructor-name-of-object)

This could then break the id creation, because it relies on `constructor.name` https://github.com/pyscript/pyscript/blob/8c65cad209ed91f4bc8e0f5ebecf877bd29d3de2/pyscriptjs/src/components/base.ts#L57 

One fix could be to use the html tag name to generate the id prefix:
```js
    checkId() {
        const idPrefix = this.tagName.split("-").map(e => {
            e = e.toLowerCase();
            return e.charAt(0).toUpperCase() + e.slice(1)
        }).join("");
        if (!this.id) this.id = idPrefix + '-' + guidGenerator();
    }
```

This will work for minified code aswell

**Comment by Navaneeth-Sharma** [comment] 2022-05-15 12:58
Hi, 
I am facing similar issue. 

I observe these points
- The text are rendered sometimes when refreshed.
- The "live" server behaves the same.

Hi @yannickfunk, thank you for providing the solution. I am new to Javascript, Can you please guide where to put this snippet?

I tried adding
```html
 <script> 
    checkId() {
    const idPrefix = this.tagName.split("-").map(e => {
        e = e.toLowerCase();
        return e.charAt(0).toUpperCase() + e.slice(1)
    }).join("");
    if (!this.id) this.id = idPrefix + '-' + guidGenerator();
}
</script>
```

But didnt work.

Thank you

**Comment by rayjolt** [comment] 2022-05-15 13:51
@Navaneeth-Sharma 
> Hi yannickfunk, thank you for providing the solution. I am new to Javascript, Can you please guide where to put this snippet?

This needs to be fixed inside PyScript itself. You can't fix it inside HTML documents you create. The snippet Yannick provided is meant to be applied [here](https://github.com/pyscript/pyscript/blob/8c65cad209ed91f4bc8e0f5ebecf877bd29d3de2/pyscriptjs/src/components/base.ts#L57) in the PyScript code; please wait while the PyScript devs fix it.

**Comment by marianoweber** [comment] 2022-05-15 14:29
> ```js
> checkId() {
>     const idPrefix = this.tagName.split("-").map(e => {
>         e = e.toLowerCase();
>         return e.charAt(0).toUpperCase() + e.slice(1)
>     }).join("");
>     if (!this.id) this.id = idPrefix + '-' + guidGenerator();
> }
> ```
Hey,

just to clarify:
With this function, the Id of elements like py-script would be "#Pyscript-xyz" instead of "#PyScript-xyz", correct?
Does anyone know if that is relevant in any other parts of the project?

Thanks

**Comment by yannickfunk** [comment] 2022-05-15 14:36
> > ```js
> > checkId() {
> >     const idPrefix = this.tagName.split("-").map(e => {
> >         e = e.toLowerCase();
> >         return e.charAt(0).toUpperCase() + e.slice(1)
> >     }).join("");
> >     if (!this.id) this.id = idPrefix + '-' + guidGenerator();
> > }
> > ```
> 
> Hey,
> 
> just to clarify: With this function, the Id of elements like py-script would be "#Pyscript-xyz" instead of "#PyScript-xyz", correct? Does anyone know if that is relevant in any other parts of the project?
> 
> Thanks

No, it will still be "#PyScript-xyz".

PY-SCRIPT.split("-") => ["PY", "SCRIPT"]
.map(e.toLowercase()) => ["py", "script"]
.map(e.charAt(0).toUpperCase() + e.slice(1)) => ["Py", "Script"]
.joint("") => "PyScript"

**Comment by marianoweber** [comment] 2022-05-15 14:41
> > > ```js
> 
> > > checkId() {
> 
> > >     const idPrefix = this.tagName.split("-").map(e => {
> 
> > >         e = e.toLowerCase();
> 
> > >         return e.charAt(0).toUpperCase() + e.slice(1)
> 
> > >     }).join("");
> 
> > >     if (!this.id) this.id = idPrefix + '-' + guidGenerator();
> 
> > > }
> 
> > > ```
> 
> > 
> 
> > Hey,
> 
> > 
> 
> > just to clarify: With this function, the Id of elements like py-script would be "#Pyscript-xyz" instead of "#PyScript-xyz", correct? Does anyone know if that is relevant in any other parts of the project?
> 
> > 
> 
> > Thanks
> 
> 
> 
> No, it will still be "#PyScript-xyz".
> 
> ```js
> 
> "PY-SCRIPT".split("-") // => ["PY", "SCRIPT"]
> 
> .map(e.toLowercase()) // => ["py", "script"]
> 
> .map(e.charAt(0).toUpperCase() + e.slice(1)) // => ["Py", "Script"]
> 
> .join("") // => "PyScript"
> 
> ```

Got it, somehow overlooked the first split... thanks for the clarification.

**Comment by yannickfunk** [comment] 2022-05-16 13:49
@marimeireles In case this is missed, could you give the issue title a [BUG] tag and add the bug label?

**Comment by fpliger** [comment] 2022-05-16 16:10
@kumargautam99  can you try now? #395 should have temporarily fixed it (although we need to investigate to actually come with a better fix)

**Comment by kumargautam99** [comment] 2022-05-16 17:08
Thanks for looking into it but the issue still persists.

Below is the error message.











*pyodide.asm.js:14 Uncaught (in promise) PythonError: Traceback (most
recent call last):  File "<exec>", line 164, in write  File "<exec>", line
116, in writeJsException: SyntaxError: Failed to execute 'querySelector' on
'Document': '#-80d2aff4-9486-153b-aff3-39d1e597fc8c' is not a valid
selector.    at new_error (pyodide.asm.js:14:238191)    at
pyodide.asm.wasm:0xedbcb    at pyodide.asm.wasm:0xedccc    at
Object.Module.callPyObjectKwargs (pyproxy.gen.ts:374:12)    at
Proxy.callKwargs (pyproxy.gen.ts:1167:19)    at z.evaluate
(pyscript.js:1:5845)*

[image: image.png]

**Comment by kumargautam99** [comment] 2022-05-16 17:44
Tried both (incognito browser and cache flush), the issue persists.

Below is the sample code which i am using inside google chrome.
`<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body>
      <py-script>
print("Let's compute π:")
def compute_pi(n):
    pi = 2
    for i in range(1,n):
        pi *= 4 * i ** 2 / (4 * i ** 2 - 1)
    return pi

pi = compute_pi(100000)
s = f"π is approximately {pi:.3f}"
print(s)
      </py-script>
  </body>
</html>`

**Comment by fpliger** [comment] 2022-05-16 18:23
@kumargautam99  Not sure I understand. This, pointing to the cdn,  works just fine. What am I missing?

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <title>Reproducing #370</title>

    <link rel="icon" type="image/png" href="favicon.png" />
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>

  <body>
    <py-script>
print("Let's compute π:") 
def compute_pi(n): 
    pi = 2
    for i in range(1,n): 
        pi *= 4 * i ** 2 / (4 * i ** 2 - 1) 
        return pi
pi = compute_pi(100000)
s = f"π is approximately {pi:.3f}"
print(s)
    </py-script>
  </body>
</html>
```

Can you paste your full example?

**Closed** 2022-05-16 21:08 UTC
Labels: type: bug

**Comment by rayjolt** [comment] 2022-05-17 01:06
I tested again with [the code I posted above](https://github.com/pyscript/pyscript/issues/370#issuecomment-1126654193), and I can confirm that the issue is fixed. Thank you for your work on this.

**Comment by fpliger** [comment] 2022-05-17 02:27
Awesome! Thank you @rayjolt !

**Comment by Navaneeth-Sharma** [comment] 2022-05-17 18:06
Thank you @fpliger and community ! The issue is resolved!
