### ISSUE TITLE
to do list demos do not work out of the box

### ISSUE THREAD

**Issue by pleabargain** [pyscript/pyscript#220] opened 2022-05-05 07:38 UTC
Here's the video
https://youtu.be/5AcN-PuvRWU

**Comment by JeffersGlass** [comment] 2022-05-05 16:36
You say in the video that you're running the examples by hitting F5, using (I think) the built-in VS Code live server. Does it work if you[ install the NPM dependencies](https://github.com/pyscript/pyscript#how-to-contribute) and use `npm run dev`?

**Comment by antocuni** [comment] 2022-05-06 13:10
Yes, the problem is that VS Code opens the file directly from the filesystem. If you serve the file from a webserver (either in production or a local development webserver) the example work.
#257 explains better the issue and shows a workaround.

Marking as a duplicate.

**Closed by antocuni** 2022-05-06 13:10 UTC
