### ISSUE TITLE
<py-config> errors are failling silently inside pytest

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#853] opened 2022-10-13 20:35 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

While running tests that fail with `py-config` pytest won't be able to catch them.
It seems like it's just throwing a `div` in the page, but nothing really on the terminal. I wonder if that's the issue?

See attached image for more info on what I'm seeing.

<img width="1276" alt="Screenshot 2022-10-13 at 22 32 52" src="https://user-images.githubusercontent.com/17600982/195705133-ef029e88-f2fa-439f-b4f4-c6eb45f67aa0.png">

**Comment by antocuni** [comment] 2022-10-14 09:12
good catch! I have modified the title to be more descriptive, because this is a problem which is related only to our test machinery.
The explanation is simple: you don't see anything on the terminal simply because we don't print anything 😅. The relevant code is here:
https://github.com/pyscript/pyscript/blob/0e490485c828d0100371d04af419bd169df72825/pyscriptjs/src/utils.ts#L50-L65

As you see, it just creates a `div`. I think it would be good to also log the message to `console.error()`, and in that case it would be automatically shown also inside pytest.

And of course, we need a test to check the intended behavior ;)

**Comment by FabioRosado** [comment] 2022-11-14 19:37
I think we can close this issue now? The refactoring and tests that antonio created seem to cover this case. The banner also logs to console by default, so if you try to use a bad config you get the following error in the console now:

```
[Error] The config supplied: - matplotlib
 is an invalid TOML and cannot be parsed: SyntaxError: Expected "=" or Whitespace but "m" found.
	_createAlertBanner (pyscript.js:1116)
	withUserErrorHandler (pyscript.js:1153)
	(anonymous function) (pyscript.js:26153)
	Global Code (pyscript.js:26163)
```

**Comment by antocuni** [comment] 2022-11-15 22:09
uhm, that's a good question.
Currently you are only getting the error in the console but the test itself doesn't fail, because it's not a JS exception.
I wonder whether we should change the behavior of `UserError`: currently we catch it, display the banner and stop the execution "cleanly", but maybe it's a better idea to just rethrow it.
For the end user it wouldn't change much (they would see the error banner and the execution stops), but it would make tests more robust.

(Note: I did some refactoring around `UserError` in #938 )

**Closed** 2023-12-06 20:33 UTC
Labels: type: bug
