### ISSUE TITLE
[next] <py-config> and <script type="py" worker> don't work together

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1699] opened 2023-09-13 16:15 UTC
Consider the following example:
```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>PyScript Error</title>
        <script type="module" src="https://cdn.jsdelivr.net/npm/@pyscript/core@latest"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@pyscript/core/dist/core.css">
        <py-config>
          [[fetch]]
          files = ["pyterminal.py"]
        </py-config>

        <script type="py" worker>
          print('hello')
        </script>
    </head>
</html>
```

I see a very obscure error in the console:
![image](https://github.com/pyscript/pyscript/assets/344507/e493a299-58fb-4bdd-94ad-31ea25d5d100)

**Comment by WebReflection** [comment] 2023-09-13 16:29
yeah ... the `worker` is handled in a different way because any worker can have any config, not just one, as any worker is a different world and different pyodide compared to main ... as worker is a new thing and very well documented in what it does and how, I don't think this is a release blocker but I fully see your point ... it's hard to couple at distance custom types with completely unrelated things custom types could do (`<py-config>` in this case) but I'll see tomorrow if there's any way that's not extremely ugly to somehow "bind" this expectation via *polyscript*.

**Comment by WebReflection** [comment] 2023-09-13 16:32
P.S. my thinking is that in your case, you pass a `config="py-config"` as selector to the worker, but no extra magic seems possible to me from a general purpose *enabler* as *polyscript* is ... happy to hear other suggestions, 'cause "leak globally that thing and let polyscript know that's the default config to use" doesn't feel like the best approach to me ... but I haven't gaven me enough time to think about this.

**Comment by WebReflection** [comment] 2023-09-13 16:34
P.S.2 OK ... I think *polyscript* can have a `workerConfig` field for custom types and use that out of the box when no config is explicitly provided. This feels nice and clean to me, I'll do my best tomorrow.

**Comment by WebReflection** [comment] 2023-09-13 18:44
it doesn't fail because it's expected to work like that ... but this feature can be supported and it makes sense to test right away via `worker` attribute if anything can be moved into a worker instead.

**Comment by WebReflection** [comment] 2023-09-13 18:47
uhm wait ... now I am confused about what is this ... is this about worker not caring that config or is this about the worker (currently ignoring it completely) not showing an error on the DOM? :thinking: 

the former is by design, the latter is either a py-config thing that has nothing to do with the `worker` attribute or already listed as nice to have in this issue https://github.com/pyscript/pyscript/issues/1678

so ... what is it that you are after? 3 scenarios here!

**Comment by antocuni** [comment] 2023-09-14 07:46
> is this about worker not caring about that config or is this about the worker (currently ignoring that config completely) not showing an error on the DOM? 🤔

my point is that I don't really understand what's happening. You say that the worker completely ignores py-config but it's not true: if I comment out the py-config, `hello` gets printed.
So, the py-config somehow prevents the worker to run.

And in any case, this is a bug report about "we should report our errors better".

**Comment by WebReflection** [comment] 2023-09-14 08:49
config parsing is at the very core/bootstrap of the project ... config is there and fails, everything fails.

In this issue the topic is unrelated because `worker` attribute or tags with that attribute don't use the config in the page.

If we want these to use the config in the page that's an issue a part.

If we want to provide better errors on config failures that's duplicated issue so we should close this.

**Comment by WebReflection** [comment] 2023-09-14 08:50
P.S. I will test locally what's going on and see if there is something I am overlooking here ... yet I am pretty sure the worker doesn't care about the config in the page but maybe I've implemented it and forgot about it :sweat_smile: 

I'll keep this open until further investigation.

**Comment by WebReflection** [comment] 2023-09-14 08:57
This MR is a blocker for this one https://github.com/pyscript/pyscript/pull/1698

It needs to go in otherwise we don't have the error plugin when the config error eventually happens (or the bootstrap fails)

**Comment by antocuni** [comment] 2023-09-14 14:36
Sorry, maybe today I am a bit slow, but I still don't fully understand what is the "by design" behavior.
My question is: 
what do we expect to happen if I have a *valid* `<py-config>` tag and a `<script type="py" worker>` tag?

Possible answers:
1) py-config is ignored and the worker is executed as if py-config didn't exist
2) it is an error to have both py-config and a worker in the same page, so the execution should stop

**Comment by WebReflection** [comment] 2023-09-14 18:57
> what do we expect to happen if I have a valid <py-config> tag and a <script type="py" worker> tag?

by design right now, nothing ... every worker can have its own py-config.

do we want to propagate the main py-config thing to any worker as default? fine, works for me, you just need to understand that from a separation of concerns point of view from my Web side of thinking, workers never had anything to do with the main thread ... so `worker` attribute with no file to parse stuff elsewhere? Already a stretch to the initial design ... random configuration on the main that should drill down elsewhere worlds? Another thing I've never thought about.

I'm OK with your expectations though, as that aligns with the empty `worker` attribute and content elsewhere state of affairs.

**Comment by WebReflection** [comment] 2023-09-14 19:01
P.S. by no mean a py-config should be merged in workers world if a different config is passed, or we're into slippery slope worlds incapable of separating main world needs from workers needs, as these can coexist at the same time with *Next*.

**Comment by antocuni** [comment] 2023-09-14 20:19
>> 1. py-config is ignored and the worker is executed as if py-config didn't exist

> in short is answer number 1 by design, right now.

ok, then I claim that the current code does NOT do that :).
Proof:
https://pyscript.com/@antocuni/worker-and-py-config/latest

```html
        <py-config>
          [[fetch]]
          files = ["pyterminal.py"]
        </py-config>

        <script type="py" worker>
          print('hello')
        </script>
```

If I understand correctly your explanation, in this example the py-config should be ignored and the worker should be executed normally.

However, if you try to execute it, the `hello` is never printed, and in the console I see an obscure message:
![image](https://github.com/pyscript/pyscript/assets/344507/471b75f0-8fb0-4697-a71d-e1b159bde2b7)

- if I comment out the `<py-config>` tag, the `hello` is printed.
- if I *remove* the `worker` attribute, the `hello` is printed
- the combination of py-config + the `worker` attribute causes problems

**Comment by WebReflection** [comment] 2023-09-14 21:08
I still need to check this locally ... I've been focused on other topics today so I won't answer until I get a chance to understand what's going on with latest *next* state and latest *config* parsing in it.

**Comment by WebReflection** [comment] 2023-09-19 12:54
Found the culprit and it was *polyscript* badly handling configs that were not links or anything useful.

This MR fixes your issue https://github.com/pyscript/pyscript/pull/1726

About propagating the `<py-config>` to workers I think we should file a new issue and maybe discuss what we expect there but current MR is still needed as other things were broken with the custom config type.

**Comment by WebReflection** [comment] 2023-09-19 12:55
P.S. I never meant to close this until it's actually fixed in PyScript ... not sure what happened there ..

**Comment by WebReflection** [comment] 2023-09-19 14:10
OK, this is out of draft and everything is awesome :partying_face:  https://github.com/pyscript/pyscript/pull/1726

**Comment by WebReflection** [comment] 2023-09-19 19:20
MR landed.

**Closed by WebReflection** 2023-09-19 19:20 UTC

**Comment by antocuni** [comment] 2023-09-20 09:12
> P.S. I never meant to close this until it's actually fixed in PyScript ... not sure what happened there ..

I think that github automatically closed it because the MR said `Fix #nnn`

**Comment by WebReflection** [comment] 2023-09-20 09:19
Very possible but it came from *polyscript* not from this repo ... lesson learned, I suppose :D

**Comment by antocuni** [comment] 2023-09-20 09:25
Ok, it's this commit which contains the "culprit" message, and it's indeed inside the pyscript repo:
https://github.com/pyscript/pyscript/commit/e8d5138cfafa08f4bae11d32332a2fbb5e2922f1

**Comment by WebReflection** [comment] 2023-09-20 09:31
Wow, that never worked to date, I thought it came [from here](https://github.com/pyscript/polyscript/pull/41#issue-1902899707) ... case solved, thanks! (actually happy that worked, I've written that before but somehow it wasn't following up ... I'll use that trick next times).
