### ISSUE TITLE
[NEXT] py-script via unpkg/esm.sh CDNs not working

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript#1688] opened 2023-09-09 17:57 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm getting the following error

```
VM4369 core.js:3 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "py-script" has already been used with this registry
    at https://unpkg.com/@pyscript/core@0.1.11/dist/core.js:3:3740
```

when I run the following in the current build published on `esm.sh` or `unpkg.com` 

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Example</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script type="module" src="https://unpkg.com/@pyscript/core"></script>
</head>
<body>
    <py-script async src="./main.py"></py-script>
</body>
</html>
```

where `main.py` is:

```python
print("Hello")
```

and the same happens if the code is defined inline `<py-script async >print("Hello")</py-script>`

If the code is set to run on a worker, everything works. So, by comparison, the following does work:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Example</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script type="module" src="https://unpkg.com/@pyscript/core"></script>
</head>
<body>
    <py-script async worker="./main.py"></py-script>
</body>
</html>
```

**Comment by WebReflection** [comment] 2023-09-10 11:52
There is a `test/async.html` file that works just fine, you can change it as such:

```html
<!doctype html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="../dist/core.css">
        <script type="module" src="../dist/core.js"></script>
    </head>
    <body>
        <py-script async src="./a.py"></py-script>
    </body>
</html>
```

and it's all good.

On the other hand, it'd be great to provide errors in console because this is a CDN issue, not a PyScript Next one.

Try `https://cdn.jsdelivr.net/npm/@pyscript/core/dist/core.js` instead and everything should be fine.

**Comment by WebReflection** [comment] 2023-09-10 11:54
P.S. this reminds me we really need to change all examples to use the CDN we want and we know that works ... every CDN seems to do weird stuff we don't really control.

**Comment by WebReflection** [comment] 2023-09-10 12:13
I did investigate a little ... here the situation:

## unpkg

This url works https://unpkg.com/@pyscript/core@0.1.11/dist/core.js but the default one resolves in a way that loads core.js twice: broken and undesired + no sourcemap available in there

![Screenshot from 2023-09-10 14-03-06](https://github.com/pyscript/pyscript/assets/85749/de650c40-620b-42fd-8a0a-37254f81a876)

## esm.sh

This one is fully broken: it takes over our dist folder and re-bundle in the error file (see its size) core twice: undesired and broken by design

![Screenshot from 2023-09-10 14-08-10](https://github.com/pyscript/pyscript/assets/85749/4b488277-e618-495d-b24d-0d1a7daa0e5b)

I think the solution here is to write explicitly in the documentation the CDN url we want people to use, like pretty much any other *Getting Started* documentation page suggests.

I will, however, file bugs to these CDNs as they really should:

  a. mind their business out of a dist folder (or tell me how to hint that in the `package.json`)
  b. do not ever re-bundle anything as we provide sourcemap and optimized files already ... these "*smart CDNs*" break too easily

**Comment by WebReflection** [comment] 2023-09-10 12:16
I am re-opening this to keep it visible but with the right flags too

**Comment by WebReflection** [comment] 2023-09-11 09:35
Filed 2 issues:

  * [unpkg.com](https://github.com/mjackson/unpkg/issues/371)
  * [esm.sh](https://github.com/esm-dev/esm.sh/issues/720)

**Comment by WebReflection** [comment] 2023-09-11 09:43
FYI I've also published this MR to see if anything changes or improve, as there are more fields usable to hint CDNs what and where to find files: https://github.com/pyscript/pyscript/pull/1690

**Comment by WebReflection** [comment] 2023-09-11 14:10
Mentioned MR fixed **unpkg** so that `https://unpkg.com/@pyscript/core` just works now *except* for *worker* use cases because it doesn't enable the right headers.

**Comment by WebReflection** [comment] 2023-09-12 11:52
OK, this MR fixes jsdelivr links too https://github.com/pyscript/pyscript/pull/1693 and the only fully broken CDN is `esm.sh` because it's incapable of not re-bundling plugins with the whole core each time. Removed from PyScript Next documentation, I will follow up with polyscript links too soon.

**Comment by WebReflection** [comment] 2023-09-13 13:22
I can confirm importing `https://cdn.jsdelivr.net/npm/@pyscript/core` just works now, so I think we can close this issue as also docs around core have been updated with better links.

**Closed by WebReflection** 2023-09-13 13:22 UTC
Labels: 3rd party
