### ISSUE TITLE
`script_element.process()` function not working

### ISSUE THREAD

**Issue by samueller** [pyscript/pyscript#2155] opened 2024-09-04 15:39 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I'm trying to programmatically execute code in a `<py-editor>` using [the documentation for `editor.process(code)`](https://docs.pyscript.net/2024.8.2/user-guide/editor/#read-write-execute).

I get the following error when executing `editor.process(editor.code)`:
```
pyodide.asm.js:10
Unable to use `window` or `document` -> https://docs.pyscript.net/latest/faq/#sharedarraybuffer
```
### mre.html
```html
<!doctype html>
<html>
	<head>
		<link
			rel="stylesheet"
			href="https://pyscript.net/releases/2024.8.2/core.css"
		/>
		<script
			type="module"
			src="https://pyscript.net/releases/2024.8.2/core.js"
		></script>
	</head>
	<body>
		<script type="py-editor" id="editor">
			import sys
			print(sys.version)
		</script>
		<script type="py" src="mre.py"></script>
		<button py-click="submit">Submit</button>
	</body>
</html>
```
### mre.py
```python
from pyscript import document


def submit(event):
    editor = document.querySelector('#editor')
    editor.process(editor.code)
```
I've tried making the `submit` function `async` and `await`ing `editor.process(editor.code)`. I've also tried using micropython instead of pyodide. I've even tried `process`ing the editor's code from JavaScript according to #2053 :
```javascript
<script>
addEventListener('mpy-editor', async (event) => {
    // the script is the target of this event
    const { target: script } = event
    // it can process any Python code
    await script.process('print("hello")')
})
</script>
```
Everything results in the same error message above.

### What browsers are you seeing the problem on? (if applicable)

Chrome

### Console info

```shell
pyodide.asm.js:10
Unable to use `window` or `document` -> https://docs.pyscript.net/latest/faq/#sharedarraybuffer
```

**Comment by WebReflection** [comment] 2024-09-05 15:28
that's a **warning** about the fact you are not enabling *SharedArrayBuffer* and the link showed in such warning should provide all the details you need: https://docs.pyscript.net/latest/faq/#sharedarraybuffer

Unless you are sure you are enabling all headers needed to have 100% PyScript working, I am going to close this. If you do, feel free to re-open or comment so I'll take a look, thanks.

**Comment by samueller** [comment] 2024-09-06 03:22
I was able to satisfy that warning by using the [mini-coi](https://github.com/WebReflection/mini-coi#readme) project and also by adding the `service-worker` attribute to the `py-editor` `script` and pointing it to the [sabayan Service Worker](https://raw.githubusercontent.com/WebReflection/sabayon/main/dist/sw.js).

In both cases, while the warning went away, nothing was output to the output `div` or to the console. I would've expected that the output `div` would be updated. Python error stacktraces are also not output anywhere I could find.

The Python code in the `py-editor` does get run, because I was able to update the DOM:
```python
from pyscript.web import page, div

page.append(div('hello'))
```
Is the expectation for `script_element.process()` that we override all output functions, like `print`, and intercept exceptions?

**Comment by WebReflection** [comment] 2024-09-06 08:11
> The Python code in the py-editor does get run, because I was able to update the DOM:

great, so if your example works, that was the issue, missing headers to allow main thread access from workers.

> Is the expectation for script_element.process() that we override all output functions, like print, and intercept exceptions?

the py-editor lives in a worker to avoid blocking your main thread if you write an infinite loop, as example, plus other things ... the expectation of evaluating its content is the same as pressing the *Run* button except it doesn't need an explicit user intent. This is (or better, *should*) be documented in our docs and it's also tested and used in production already so it'd be surprising if something is not working as I know projects using that quite a lot.

So, assuming you understand how the PyEditor works, and yes ... it does take over the `print` and shows its things on its related target, created by default if not available, what is it that is surprising you?

Any **minimal** reproducible example might help me to understand and help you fix that ... or me fixing what's broken, thanks.

**Comment by samueller** [comment] 2024-09-06 17:47
> what is it that is surprising you?

My MRE is posted above. If you click the green _run_ button, the following is printed in the div below the editor:
```
3.12.1 (main, Jul 26 2024, 14:03:47) [Clang 19.0.0git (https:/github.com/llvm/llvm-project 0a8cd1ed1f4f35905df318015b
```
If, instead of clicking the green _run_ button, you click the Submit button (which calls `editor.process(editor.code)`, nothing is printed anywhere (neither in the output div nor in the console).

**Comment by WebReflection** [comment] 2024-09-07 11:42
is the submit reloading the page or you are doing `event.preventDefault()` in its listener/related form?

**Comment by samueller** [comment] 2024-09-07 14:25
The page is not being reloaded, a button outside a form wouldn't cause a reload, as seen in Chrome dev tools. Also, any print statements before and after `editor.process(editor.code)` are shown and remain in the console. In any event, I also added the following code and I still get the same issue:
```javascript
document
    .querySelector('button')
    .addEventListener('click', (event) => event.preventDefault())
```

**Comment by samueller** [comment] 2024-09-13 23:06
For convenience, I've attached the MRE zip containing 2 files (`mre.html` and `mre.py`), including `<script src="/mini-coi.js"></script>` and the `event.preventDefault()` code above.
[mre.zip](https://github.com/user-attachments/files/17000035/mre.zip)

Essentially, nothing is `print`ed in the output `div` as expected (nor is anything printed anywhere else). Should this issue be reopened?

**Comment by WebReflection** [comment] 2024-09-15 12:30
Reopening to have deeper investigation

**Comment by WebReflection** [comment] 2024-09-18 11:12
@samueller OK, I had a look ... the current status of `editor.process(code)` is that it puts the `editor` in a `setup` like mode while evaluating the code.

This was a requirement by the time I've implemented it and it was the desired behavior, meaning:

  * a setup node has no side-effects on the page when `print` statements execute because setup nodes don't have a target and are supposed to silently bootstrap indeed
  * errors within a setup node are visible on the page because setup nodes have no target ... you won't see the error in the DOM within your target for the editor, you'll see a notification error which is something else
  * ... also ...
  * it's been asked more than once how to easily invoke the *Run* button and the workaround is to use *CSS* selectors but I see an opportunity here to instead change the `process(code)` signature to `process(code, asRunButtonAction = false)` where if that second argument is `true` instead (or `True` in Python) then it will just click on behalf of the user the *Run* and the flow is exactly the same as clicking manually *Run* which is apparently what you expect here.

Would this work as solution? I have already a working patch for it but I want to be sure that's what you are asking: a way to run the editor without the user needing to reach the editor *Run* button ... correct?

If not, please explain what you expect from `execute` as either it runs in *setup mode* or it runs through the button and the usual orchestration with the visible target on the DOM, thanks.

**Comment by WebReflection** [comment] 2024-09-19 07:49
@samueller ? 🤔

**Comment by samueller** [comment] 2024-09-20 01:39
This is great @WebReflection, thank you. `process(code, asRunButtonAction = false)` would solve our use case. We're trying to create an education platform, teaching Python. So, in addition to a Run button, we need a Submit button that runs tests against student code.

**Comment by WebReflection** [comment] 2024-09-20 08:14
It's up and running as MR. Once that gets approved, I'll publish a preview version on *npm* you can use for testing purposes, validating the current change actually solves your issue, thanks.

**Comment by WebReflection** [comment] 2024-09-20 12:12
@samueller the current *npm* version reflects these changes:

  * **JS** @ `https://cdn.jsdelivr.net/npm/@pyscript/core@0.5.13/dist/core.js`
  * **CSS** @ `https://cdn.jsdelivr.net/npm/@pyscript/core@0.5.13/dist/core.css`

**Closed** 2024-09-20 13:42 UTC
Labels: type: bug, needs-triage
