### ISSUE TITLE
Firefox renders the pyscript element with tons of unwanted space.  

### ISSUE THREAD

**Issue by axiomtutor** [pyscript/pyscript#1639] opened 2023-08-16 17:35 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I just booted up a fresh hello world project from pyscript.com, and everything basically works.  The problem is that Firefox renders the pyscript element with tons of white space, pushing it partially off of the screen.  [EDIT: I also just tried this on Chrome and it renders funky there too -- is this a feature not a bug?]

![Screenshot from 2023-08-16 13-32-17](https://github.com/pyscript/pyscript/assets/27108390/951ff54c-d9ab-4598-9bac-27f925fb4f83)

And this occurs not just in the editor, but also when loading the page directly.

![Screenshot from 2023-08-16 13-33-01](https://github.com/pyscript/pyscript/assets/27108390/b86fc676-158c-4adf-a1e9-8ef5557cc544)

### What browsers are you seeing the problem on? (if applicable)

Firefox

**Comment by FabioRosado** [comment] 2023-08-19 09:07
Hello, 

from pyscript 2023.5.1 the terminal where you can see print statements is docked to the bottom of the page. You can change this behaviour by:
- setting `docked` to false on your py-config
- setting `terminal` to false on your py-config

For reference [here's an example to change the py terminal](https://docs.pyscript.net/latest/reference/plugins/py-terminal.html#examples).

Just putting it here in case it helps, if you don't want the terminal but just want to display text on the page, you can use the [`display` API](https://docs.pyscript.net/latest/reference/API/display.html), for example:

```
<py-script>
    def display_hello():
        # this works because we give an explicit target
        display('hello', target="helloDiv")
</py-script>
<div id="helloDiv"></div>
<button id="my-button" py-click="display_hello()">Click me</button>
```

I hope this helps, I'm closing this issue since this is expected behaviour but please feel free to reopen or comment if you need further help 😄 👍

**Closed by FabioRosado** 2023-08-19 09:07 UTC
Labels: type: bug, needs-triage
