### ISSUE TITLE
Getting Dataset from online url not working :

### ISSUE THREAD

**Issue by WanjohiChristopher** [pyscript/pyscript#214] opened 2022-05-05 05:59 UTC
While i read daset from this url it doest work:

![Screenshot from 2022-05-05 09-01-37](https://user-images.githubusercontent.com/55980747/166870102-b8feb88a-fab6-4979-8720-caf7bfcd4423.png)

**Comment by WanjohiChristopher** [comment] 2022-05-05 06:08
Here is the code.
```
<html>
    <head>
      <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
      <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <py-env>
        - numpy
        - pandas
      </py-env>
    </head>
  <body>
    <h1>Dataset Preview From Online Url</h1>
    <py-script>
import pandas as pd
shopify=pd.read_csv("https://bit.ly/ShoprityDS")
print(shopify.head())
    </py-script>
  </body>
</html>
```

**Comment by bmeares** [comment] 2022-05-05 21:25
I believe the issue is due to the Python runtime being [compiled without SSL support](https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl). For example, I'm unable to [import `ssl`](https://stackoverflow.com/questions/54926396/urllib-error-urlerror-urlopen-error-unknown-url-type-https), so that explains why we can't download files over HTTPS.

**Comment by bmeares** [comment] 2022-05-05 22:49
After a bit more digging, this seems like a restriction of the underlying WASM Pyodide runtime not having access to synchronous I/O over sockets. From what I can tell, the way that Pyodide is able to communicate over the network is through JS and passing it to Python since they share namespaces. At least that's how I suspect `micropip.install()` works.

**Comment by rvalenzuelar** [comment] 2022-05-06 15:36
Same issue here. Is there any workaround?

**Comment by philippjfr** [comment] 2022-05-06 15:52
I'll close as a duplicate of https://github.com/pyscript/pyscript/issues/91. The basic answer is that requests and most other networking libraries will not work in pyodide because the networking stack is completely different. For now you can however do something like this:

```python
import pandas as pd

from pyodide.http import open_url

shopify=pd.read_csv(open_url("https://bit.ly/ShoprityDS"))
print(shopify.head())
```

**Closed by philippjfr** 2022-05-06 15:52 UTC
Labels: duplicate
