### ISSUE TITLE
local packages not loading

### ISSUE THREAD

**Issue by Keshav7aug** [pyscript/pyscript#202] opened 2022-05-04 20:30 UTC
Whenever I try to load a local packages, the python code doesn't run, I even tried copy-pasting the code given in Getting Started, also tried cloning and running files in example, but they do not work either.  If I copy paste the same code in html file it runs, but not using separate python file. I have included file in py-env.

**Comment by verhulstm** [comment] 2022-05-04 21:18
hi,

you might be seeing the same issue here

https://github.com/pyscript/pyscript/issues/171

**Comment by verhulstm** [comment] 2022-05-04 21:18
it might be this

currently the zip download does not include a pre-built pyscript.js file

you can build from source or change the html examples to point to the publicly hosted js file  

in your zip, you should find html like this (in the examples)

```
<link rel="stylesheet" href="../build/pyscript.css" />
<script defer src="../build/pyscript.js"></script>
```

change to

```
<link rel="stylesheet" href="https://pyscript.net/alpha//pyscript.css" />
<script defer src="https://pyscript.net/alpha//pyscript.js"></script>
```

**Comment by Keshav7aug** [comment] 2022-05-05 04:42
I have been using publicly hosted js file, here is my code
![image](https://user-images.githubusercontent.com/38023387/166864627-d35d1f3a-d279-4404-856d-f2c6873638e6.png)

**Comment by pleabargain** [comment] 2022-05-05 04:49
> I have been using publicly hosted js file, here is my code ![image](https://user-images.githubusercontent.com/38023387/166864627-d35d1f3a-d279-4404-856d-f2c6873638e6.png) on webpage Let's plot random numbers is shown, after that it's blank

Give it awhile. I noticed the same thing... it took time for it to load the graph on my machine too.

**Comment by Keshav7aug** [comment] 2022-05-05 04:53
the page is like that since last 10 minutes

**Comment by Keshav7aug** [comment] 2022-05-05 15:45
it is working by using live server extension in VS Code.

**Comment by marimeireles** [comment] 2022-09-08 11:23
Closing it as dup. please redirect any questions related to the topic to the [documentation issue](#756 ).
If you're facing a different problem or think might have encountered a bug please feel free to open a new issue.
If I misinterpreted your issue and you think it should still be open please reply here and we'll reopen it.
Thank you!

**Comment by marimeireles** [comment] 2022-09-29 13:47
Closing this because I can't reproduce.
Feel free to reopen if it's happening.

**Closed by marimeireles** 2022-09-29 13:47 UTC
Labels: waiting on reporter
