### ISSUE TITLE
Printing in the same line isn't working

### ISSUE THREAD

**Issue by DorkYBru** [pyscript/pyscript#472] opened 2022-05-27 20:20 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

I tried to print in the same line with for loop.
`def print_slow(str):
    for letter in str:
        print(letter,end='')
        time.sleep(0.1)`
But apart from that sys.stdout.flush() doesn't work it's still printing out vertically.

### What browsers are you seeing the problem on? (if applicable)

Firefox, Chrome

**Comment by Siddharth1India** [comment] 2022-05-28 12:01
Can you please post complete code with HTML?

**Comment by fdemmer** [comment] 2022-05-28 17:19
Complete HTML:

```
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body> 
    <py-script> 
      for n in range(0, 5):
        print(f'Hello, World {n}!', end='') 
    </py-script> 
  </body>
</html>
```

The issue is, that `print()` inserts two `div` for each time it is called: one with the string to print and one for whatever `end` is.

![image](https://user-images.githubusercontent.com/630975/170835972-ab133baf-c81c-4e9e-a60f-a24821bfee89.png)

**Comment by Siddharth1India** [comment] 2022-05-29 03:22
@fdemmer 's approach is perfect to print in same line. 
I am not sure if time module will work here or not.

**Comment by nmstoker** [comment] 2022-05-29 14:32
For the time delayed updates you need to use asyncio. First import it and then use as here:

`await asyncio.sleep(1)`

I've got a mini example that displays output updating in the same space over time here: https://about.nmstoker.com/emoji.html
(use view source to see the details 🙂)

**Comment by patpragman** [comment] 2022-05-31 03:37
I've experienced similar behavior as well.

```
<py-script>
    for i in range(0,100):
        print('Hello World!', i)
</py-script>
```
![image](https://user-images.githubusercontent.com/70462152/171087778-09c0286c-2510-4aad-a49e-6d1762a5b19d.png)



By the way, I have to add, this is such a minor gripe as to be irrelevant, but yah.  I'm immensely impressed by this project.

**Comment by FarooqAlaulddin** [comment] 2022-06-05 10:53
- Ran into the same behavior. To print a two dimensional array:


![image](https://user-images.githubusercontent.com/37892823/172047123-111b61ff-6942-40bf-afc8-1ee049a3a87f.png)
![image](https://user-images.githubusercontent.com/37892823/172047143-64cf877e-fe09-4391-acfd-d3c316ec9e7c.png)

**Comment by JeffersGlass** [comment] 2022-06-13 15:15
These issues are related to #103 - Pyscript interrupts all writes to `stdout` and creates a new `div` for each.

`print()` writes to `stdout` once for each object it's given, plus additional writes for each `sep` and `end`. Hence all the multi-div outputs given.

Exactly how output might be managed in the future, when using builtins like `print`, is probably a topic for open discussion.

**Comment by marimeireles** [comment] 2022-09-06 12:03
I think the https://github.com/pyscript/pyscript/pull/749 will fix it.
Just linking it here so we can keep it in mind to check it.
After the redesign print will only output for the console and if you want to have things on the HTML you should use display :)
This is an interesting test case scenario tho, anyway, that we should create.

**Comment by marimeireles** [comment] 2022-10-17 15:34
This doesn't work and I have no idea why.
Here are some interesting tests I've been running:

Works but doesn't print everything in the same line:
```
      for n in range(0, 5):
        print('✨')
        print(f'🔥🔥🔥🔥Hello, World {n}!', end='')
```

Doesn't print anything at all in the console:
```
      for n in range(0, 5):
        print(f'🔥🔥🔥🔥Hello, World {n}!', end='')
```

Works but it doesn't print on the same line:
```
      for n in range(0, 5):
        print(f'🔥🔥🔥🔥Hello, World {n}!')
```

My guess for why it doesn't print in the same line is that we're trusting on some underlying impl. by pyodide that works differently. I can look deeper into it.

Why doesn't the `end` argument works? No idea.

Why it works when I add a print statement before and then it prints the strings with 🔥 then? No idea.

**Comment by JeffersGlass** [comment] 2022-10-17 17:41
I think thereason is we've overridden stdout to point to the console.log(), and pyodide only _calls that function when it hits a newline_. From their FAQ:
> If you wish to override stdin, stdout or stderr for the entire Pyodide runtime, you can pass options to {any}loadPyodide... then every time a line is written to stdout (resp. stderr), stdout_func (resp stderr_func) will be called on the line.

This means the `end` argument works, but everything that's being writen to stdout doesn't get "flushed" to console.log() until we send it a newline.

---
For the first example, the statement `print('✨')` adds a newline after it, but the statement ` print(f'🔥🔥🔥🔥Hello, World {n}!', end='')` doesn't. So we end up with:

![image](https://user-images.githubusercontent.com/1931111/196244533-143a9db2-bd59-4477-a0f4-679c21f62e7f.png)

the final statement ("...Hello World 4") doesn't have a newline after it, so console.log isn't called and we don't see it at all.

---

For the second statement, _nothing_ prints a newline, so we don't see any output at all. But adding another print statement after it (which _does_ add a newline):
```python
for n in range(0, 5):
  print(f'🔥🔥🔥🔥Hello, World {n}!', end='')
print("Please print?")
```
![image](https://user-images.githubusercontent.com/1931111/196244858-dcbae874-ea82-4291-911a-6981ce72747f.png)

---

In the third example, each `print()` call adds a newline after itself as usual, so we see all the statements printed.
![image](https://user-images.githubusercontent.com/1931111/196245930-1469c887-64cd-41f6-bb80-40fbb7bb0bc8.png)


---

And in a bonus example, showing that what triggers console.log() is a newline, try:
```python
my_string = "One\nTwo\nThree\nFour"
print(my_string, end="")
```
![image](https://user-images.githubusercontent.com/1931111/196245670-1e8f699a-11c3-47ad-926d-9e52a7c39c88.png)

We see "One" "Two" and "Three" as separate logs, but there's no newline to follow "Four", so we don't see it.

**Comment by marimeireles** [comment] 2022-10-18 13:38
So... I think this is an upstream bug? 
@antocuni opinions?
Also thanks @JeffersGlass amazing ✨

**Comment by antocuni** [comment] 2022-10-18 21:21
> So... I think this is an upstream bug?

well, it's not a bug, it's a limitation of the environment. We decided to send `print()` to the console, and the console can emit output only one line at a time.

But also, note that the original question was very different: until few days ago, `print()` was supposed to send the output to the HTML, and this is what the OP wanted to do.
The correct way of emitting HTML now is to use `display()`, which doesn't (and shouldn't) support `end=''`.
So from this point of view, this issue can be closed as either `invalid` or `wontfix` (I'm not sure which.

But also, I think that what @DorkYBru was trying to achieve is possible to solve in a different way:
```html
            <py-script>
                import js
                import asyncio
                async def print_slow(str, target):
                    el = js.document.getElementById(target)
                    el.innerText = ''
                    for letter in str:
                        el.innerText += letter
                        await asyncio.sleep(0.1)

                await print_slow('hello', target='myoutput')
            </py-script>
            <p id="myoutput"></p>
```

this should display the text "one letter at a time" as the @DorkYBru was trying to do. I hope it helps :).

**Closed by antocuni** 2022-10-18 21:21 UTC
Labels: type: bug, backlog
