### ISSUE TITLE
Matplotlib example failed with ModuleNotFoundError on first load (possible timing issue?)

### ISSUE THREAD

**Issue by steves-dev** [pyscript/pyscript#1463] opened 2023-05-12 12:09 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

The matplotlib example (https://pyscript.net/examples/matplotlib.html) seems to have an intermittent dependency issue on first load:
![image](https://github.com/pyscript/pyscript/assets/103948996/a0eb8e05-61e0-49ba-8cce-856860153b22)

When I accessed the page a second time to copy the text for this issue, the plot loaded as expected.  Possible that the page tried to render before venv was set up? Or venv install had an intermittent issue?

### What browsers are you seeing the problem on? (if applicable)

Chrome

**Comment by WebReflection** [comment] 2023-05-12 14:19
I am afraid I cannot reproduce bu tit would be great if you could check network panel or devtools to see if there was an error in the CDN or something ... looks like timing related, yes, but I've never seen that failing myself ... very weird to debug this way. Can you reliably reproduce the error on second refresh?

**Comment by WebReflection** [comment] 2023-09-26 14:25
all our matplotlib tests and demos work as expected, closing this as there's no action for us to take.

**Closed by WebReflection** 2023-09-26 14:25 UTC
Labels: type: bug, needs-triage
