### ISSUE TITLE
Please add the module requests

### ISSUE THREAD

**Issue by Studio-Hawaii** [pyscript/pyscript#618] opened 2022-07-17 23:37 UTC
### Checklist

- [x] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project area (see the above section)

### What is the idea?

Can you add a requests module? It would make it easier to send requests to other servers and use discord web hooks in stuff.

### Why is this needed

So your website can communicate with other servers.

### What should happen?

Install the requests module.

### Additional Context

None

**Comment by JeffersGlass** [comment] 2022-07-19 01:28
Believe this is a duplicate of #364

**Comment by ntoll** [comment] 2022-07-26 13:10
Closing as a duplicate of #364.

**Closed by ntoll** 2022-07-26 13:10 UTC
Labels: type: enhancement, needs-triage
