### ISSUE TITLE
remove 'greater-than pinned version for a foreign module' in toml file

### ISSUE THREAD

**Issue by Neon22** [pyscript/pyscript#2250] opened 2024-11-18 21:54 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

As reported in #2245
the `>=` syntax for `packages` in the toml config file is no longer working in 2024.10.2 (last working in 2024.10.1)

As discussed in that issue - this feature does not work anymore.
IMHO as it doesn't work - we need to make it an error to use `>=`
E.g. `packages = ["chess>=1.9.2"]` does not work and should not be allowed.

only the ["chess'] or ["chess==1.92"] should be legal.

**Comment by WebReflection** [comment] 2024-11-19 09:07
Duplicate of https://github.com/pyscript/pyscript/issues/2245#issuecomment-2485103553 where a fix is landing already.

**Closed** 2024-11-19 10:47 UTC
Labels: type: bug, needs-triage
