### ISSUE TITLE
AttributeError: module 'pyodide_http' has no attribute 'patch'

### ISSUE THREAD

**Issue by manish7017** [pyscript/pyscript#1388] opened 2023-04-14 09:55 UTC
Source: https://docs.pyscript.net/latest/tutorials/requests.html 
Last code snippet of this page of the Documentation

**Comment by FabioRosado** [comment] 2023-04-14 10:28
Hello @manish7017  thank you for opening this issue, we already have one open and on our next release the tutorial will be fixed. Here's the right call:

`patch` should be `patch_all`
https://github.com/pyscript/pyscript/blob/main/docs/tutorials/requests.md?plain=1#L75 

Closing as duplicate of https://github.com/pyscript/pyscript/issues/1291

**Closed by FabioRosado** 2023-04-14 10:28 UTC

**Comment by manish7017** [comment] 2023-04-15 06:52
Thank you @FabioRosado for the help.
