### ISSUE TITLE
Create `createSingularError` function and substitute it in the event handler error

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript#1253] opened 2023-03-06 13:36 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

We get repetitive error warnings if the user incessantly clicks in a button attached to an event for example. We should change `displayPyException(err, el.parentElement);` to `createSingularError(err)` inside the `try/catch` function that's dealing with event errors. So instead of several equal error msgs we only get one.
The `createSingularError` function doesn't exist and should be created. It will be very similar to `createSingularWarning`, but it should look like an error :)
If you have questions, feel free to ask away

**Comment by aneesh98** [comment] 2023-03-13 06:04
Hi, I would like to work on this, will make `createSingularError` function using `createSingularWarning` as a reference.

**Comment by marimeireles** [comment] 2023-03-13 12:56
Awesome! :)
Let me know if you need help with this, happy to assist

**Comment by aneesh98** [comment] 2023-03-15 18:55
Hello @marimeireles 
I had one question, little bit confused and I am trying to understand how the warning function is being called. I setup the project in my local environment and in one of the provided examples (todo list) in the add_task function (in `pyscriptjs/examples/todo.py`) I am trying to raise a test warning (on click of Add Task button)

Here is the output:
![Screenshot from 2023-03-16 00-09-13](https://user-images.githubusercontent.com/37235937/225410348-c6fde021-9638-4875-bd7c-521757a198cc.png)

I also raised an error and got the following output:
![Screenshot from 2023-03-16 00-12-54](https://user-images.githubusercontent.com/37235937/225411412-b1382739-93a7-461a-87db-0a0bbc7bb1d6.png)

I understand that we need one single message for error too.
However I am trying to understand where the `createSingularWarning` function is being called in the case when I am trying to raise warnings.

I checked the function `createSingularWarning` and its calling `_createAlertBanner` which looks something like this:
```
switch (`log-${level}-${logMessage}`) {
        case 'log-error-true':
            console.error(message);
            break;
        case 'log-warning-true':
            console.warn(message);
            break;
    }

    const banner = document.createElement('div');
    banner.className = `alert-banner py-${level}`;

    if (messageType === 'html') {
        banner.innerHTML = message;
    } else {
        banner.textContent = message;
    }

    if (level === 'warning') {
        const closeButton = document.createElement('button');

        closeButton.id = 'alert-close-button';
        closeButton.addEventListener('click', () => {
            banner.remove();
        });
        closeButton.innerHTML = CLOSEBUTTON;

        banner.appendChild(closeButton);
    }

    document.body.prepend(banner);
```

 its trying to add an `div` element which has the class `alert-banner py-warning` but the Warning element that was created is a `py-terminal` tag
![image](https://user-images.githubusercontent.com/37235937/225413033-448e4d9f-b1aa-4fd2-8412-83b0254ec342.png)

I know that the change has to be made to replace `displayPyException` function to something like `createSingularWarning` but for error, my question is more of a curiosity for warnings :), just trying to understand how it is working.

Also please let me know if I am doing anything wrong.

Thanks.

**Comment by aneesh98** [comment] 2023-03-18 19:05
> Hello @marimeireles 
> I had one question, little bit confused and I am trying to understand how the warning function is being called. I setup the project in my local environment and in one of the provided examples (todo list) in the add_task function (in `pyscriptjs/examples/todo.py`) I am trying to raise a test warning (on click of Add Task button)
> 
> Here is the output:
> ![Screenshot from 2023-03-16 00-09-13](https://user-images.githubusercontent.com/37235937/225410348-c6fde021-9638-4875-bd7c-521757a198cc.png)
> 
> I also raised an error and got the following output:
> ![Screenshot from 2023-03-16 00-12-54](https://user-images.githubusercontent.com/37235937/225411412-b1382739-93a7-461a-87db-0a0bbc7bb1d6.png)
> 
> I understand that we need one single message for error too.
> However I am trying to understand where the `createSingularWarning` function is being called in the case when I am trying to raise warnings.
> 
> I checked the function `createSingularWarning` and its calling `_createAlertBanner` which looks something like this:
> ```
> switch (`log-${level}-${logMessage}`) {
>         case 'log-error-true':
>             console.error(message);
>             break;
>         case 'log-warning-true':
>             console.warn(message);
>             break;
>     }
> 
>     const banner = document.createElement('div');
>     banner.className = `alert-banner py-${level}`;
> 
>     if (messageType === 'html') {
>         banner.innerHTML = message;
>     } else {
>         banner.textContent = message;
>     }
> 
>     if (level === 'warning') {
>         const closeButton = document.createElement('button');
> 
>         closeButton.id = 'alert-close-button';
>         closeButton.addEventListener('click', () => {
>             banner.remove();
>         });
>         closeButton.innerHTML = CLOSEBUTTON;
> 
>         banner.appendChild(closeButton);
>     }
> 
>     document.body.prepend(banner);
> ```
> 
>  its trying to add an `div` element which has the class `alert-banner py-warning` but the Warning element that was created is a `py-terminal` tag
> ![image](https://user-images.githubusercontent.com/37235937/225413033-448e4d9f-b1aa-4fd2-8412-83b0254ec342.png)
> 
> I understand that the change has to be made to replace `displayPyException` function to something like `createSingularWarning` but for error, my question is more of a curiosity for warnings :), just trying to understand how it is working.
> 
> Also please let me know if I am doing anything wrong.
> 
> Thanks.

After searching More, I realised this is coming actually from PyTerminal Plugin.

**Comment by aneesh98** [comment] 2023-03-18 19:09
Hi @marimeireles 
I had one more question to ask

Will it be fine to modify the `displayPyException` function itself?
To check if the error message is already present in one of the elements on the web page having `py-error` class and if not then display it.
Just like `createSingularWarning` checks for elements with `py-warning` class?

Let me know if this sounds fine?

**Comment by aneesh98** [comment] 2023-03-23 05:59
Hi @marimeireles ,
Thank you so much for your reply.

I had one alternative suggestion, please let me know if this is fine. 

Will it be fine to modify the `displayPyException` function itself? It gets called in two places
1. `createElementsWithEventListeners` in file `pyscriptjs/src/components/pyscript.ts`, I guess this is the place which create elements and registers their event listeners?
2. function `pyExec` in path `pyscriptjs/src/pyexec.ts`

`displayPyException` function already creates the elements with CSS class name `py-error` and displays exception stack trace on UI in those elements.
I have added logic to check in `displayPyException` function, checking if the error message was previously rendered on the UI or not? and if not then render it.
This is pretty much similar to bannerCount logic in `createSingularWarning`

https://github.com/pyscript/pyscript/blob/ef793aecf3afad83740a3ba3a635d306518beb13/pyscriptjs/src/utils.ts#L103-L114

Here is working demo:
1. Here there are 2 buttons (`Generate Error 1` - it generates a test exception upon adding a task in input field and `Generate Error 2` - It generates another exception upon clicking it)
2. Once the Exception raised from `Generate Error 1` is displayed on UI, it is not displayed again, even after I click it multiple times, same for `Generate Error 2` button


https://user-images.githubusercontent.com/37235937/227115207-84d0c4a6-a933-4686-afac-a353e7eb8b71.mp4

I suggested to change to `displayPyException` function itself because it already creates those error elements, so maybe can tweak the function itself to render error messages only once. 

But Please let me if what I have suggested is right or wrong? 
Would be happy to make corrections :)

**Comment by marimeireles** [comment] 2023-03-30 09:34
Hi @aneesh98, sorry I said I'd be more diligent about reply times but it was my birthday so I was out for a few days!

I understand `displayPyException` shows very similar behavior to what we're trying to achieve here but the problem with using this specific function is that we want a generic function that we can also use to display exceptions on the Typescript side.

Oh, I see you've opened a PR, will rather answer through there.
Cheers, thank you for the patience.

**Comment by aneesh98** [comment] 2023-03-30 17:55
Hi @marimeireles, no problem and wish you a belated happy birthday 😄

**Comment by OdinTech3** [comment] 2023-04-24 23:12
I think I got this

**Comment by WebReflection** [comment] 2024-04-22 14:37
Late to "the party" but I think things changed so much that I'd like to either have this issue filed again or forget about it, as opposite of bothering everyone involved in this discussion.

I also think an error showed per **each** user action is actually a good one, so this issue is easily into the debatable UX/DX experience and, once again, if that's the case we need to be aligned in what an error, when or why, should happen, or what's actually broken in the current PyScript, as the classic (legacy) version is not being maintained.

I hope this reasons or makes sense to you, and I am closing this looking forward to have a modern reproducible issue to work on, and drop some handler from this conversation, as they are (unfortunately) not working on this project anymore.

I hope this is fine to you all, feel free to state otherwise or help us further with the current offer, thank you!

**Closed by WebReflection** 2024-04-22 14:37 UTC
Labels: type: bug, good first issue, classic
