### ISSUE TITLE
<py-script terminal worker> should not start a REPL

### ISSUE THREAD

**Issue by antocuni** [pyscript/pyscript#1840] opened 2023-11-03 15:48 UTC
Currently, if we request a `terminal` in a worker, it automatically starts a python REPL (by calling `code.interact()`):

```html
        <py-script terminal worker>
          print("hello world")
        </py-script>
```
![image](https://github.com/pyscript/pyscript/assets/344507/15e072eb-4780-4ea2-9315-9c42b2bb0a4b)

I think this is wrong.
There are tons of legitimate use cases for wanting just a terminal without the REPL:
1. a simple `print("hello world")` should just print `hello world`
2. a simple program which uses `input("Guess the number? ")` should not start a REPL, IMHO

Moreover, the current REPL is blocking, which means that the worker will not respond to events.
Consider the following:

```html
        <py-script terminal worker>
          from pyscript import when
          print("hello world")

          @when('click', selector="#my-button")
          def click():
              print('click!')
        </py-script>
        <button id="my-button">Click me</button>
```

When clicking on the button, nothing is printed, but chrome warns about a possible deadlock:
![image](https://github.com/pyscript/pyscript/assets/344507/cf053b20-bf8a-44dc-baaf-1589d112c688)

If I force the REPL to quit by typing `exit()`, all the queued messages/events are "correctly" delivered. In the image below, I pressed the button several times, *then* typed `exit()`
![image](https://github.com/pyscript/pyscript/assets/344507/8ce820d2-37f4-4e60-a6f6-c746c450c9ef)

**Comment by WebReflection** [comment] 2023-11-03 17:20
I'm OK with the suggested behavior, I am just not sure, implementation wise, how would that look like ... currently, the worker bootstraps Xterm in an interactive way, while the main case doesn't ... my understandingis that as the terminal can be only one, the worker with such terminal can be just the last script on the page ... or better, your presented use case would be identical after an input is invoked, leading to more surprises, because the `code.interact()` would do the exact same there, it will block the worker until it's done ... and it blocks the main via Atomics, as that's the whole feature of the interactive terminal ... so ... how do you see us fixing this, given the current status?

**Comment by JamesParrott** [comment] 2023-11-03 17:39
I'm completely new to this project (really impressed by the way - well done everyone!), but wouldn't this be a breaking change?  Haven't downstream users deployed Pysript already now, and rely on this to be the expected behaviour?

Nonetheless, I think it would be straightforward to add an extra test (e.g. an extra attribute in the html tag, such as `element.hasAttribute('noREPL')` test), to do something different with this code here:

```
        // at the end of the code, make the terminal interactive
        const codeAfter = `
            import code as _code
            _code.interact()
        `;
```

https://github.com/pyscript/pyscript/blob/3e2a67d4345edd1ca7a43e29d212b5608d1d243b/pyscript.core/src/plugins/py-terminal.js#L101C1-L105C11

**Comment by WebReflection** [comment] 2023-11-03 18:12
@JamesParrott thanks for the kind words but about your proposal, you can see the dance becoming ugly pretty soon:

```html
<script type="py" worker terminal no-repl>
  # ... code ...
</script>
```

I would be OK with the extra attribute resolution but it feels to me like a slippery slope for chaos on future extra plugins and whatnot ... that being said, the moment a worker becomes a fully interactive terminal it's code won't ever stop executing because `code.interact()` won't ever release itself from Pyodide loop so it's crucial to make everyone aware of this and also find the best approach ... this could also be we inject the `code.interact()` Python code on JS side, when the whole dance has finished already, and on a timeout, but still bootstrapping this on `input` feels like something I wouldn't personally know how to do best, hence my questions

**Comment by antocuni** [comment] 2023-11-06 10:33
> I'm OK with the suggested behavior, I am just not sure, implementation wise, how would that look like

I'm confused. You can just remove these lines, cannot you?

```diff
--- a/pyscript.core/src/plugins/py-terminal.js
+++ b/pyscript.core/src/plugins/py-terminal.js
@@ -100,8 +100,8 @@ const pyTerminal = async () => {
 
         // at the end of the code, make the terminal interactive
         const codeAfter = `
-            import code as _code
-            _code.interact()
+            #import code as _code
+            #_code.interact()
         `;
 
         // add a hook on the main thread to setup all sync helpers
```

> or better, your presented use case would be identical after an input is invoked, leading to more surprises, because the `code.interact()` would do the exact same there, it will block the worker until it's done ... and it blocks the main via Atomics, as that's the whole feature of the interactive terminal ... so ... how do you see us fixing this, given the current status?

yes, I don't think we can fix it: when `input()` is invoked, events are not dispatched. We cannot avoid and it should be documented as such.

And this alone is a good reason for not starting a REPL unless the users asks for it.

---

re @JamesParrott:
> I'm completely new to this project (really impressed by the way - well done everyone!), but wouldn't this be a breaking change? Haven't downstream users deployed Pysript already now, who rely on dropping into a REPL as the default behaviour?

no, this is a new feature which was never released before, so we are still in time to change it without breaking anything :)

**Comment by WebReflection** [comment] 2023-11-06 13:10
> And this alone is a good reason for not starting a REPL unless the users asks for it.

what if we export a `repl()` utility via *stdlib* then? it might play better for the time MicroPython can offer one too, as the rest can be already easily fixed on JS side and need branching, but same Python for different interpreters might be problematic to explain ... thoughts?

**Comment by antocuni** [comment] 2023-11-06 13:52
> what if we export a `repl()` utility via _stdlib_ then? it might play better for the time MicroPython can offer one too, as the rest can be already easily fixed on JS side and need branching, but same Python for different interpreters might be problematic to explain ... thoughts?

you mean, something like this?
```html
<script type="py" terminal>
    import pyscript
    pyscript.repl()
</script>
```

I like the idea!

**Comment by JeffersGlass** [comment] 2023-11-06 14:42
Seconded! Like the idea of `pyscript.repl()`

**Closed** 2023-11-07 18:22 UTC
